### PR TITLE
Fix broken chat view in original white theme

### PR DESCRIPTION
**Pull request by ghost**
That will remove the gray border to the bottom on the left navbar.
This is also the same design like in the profile view and SPV.

untitled

### CODE REVIEW

**Comment by AugierLe42e** [comment]
My poor @Zauberstuhl. Any time the design changes, you have to repaire the chat :p

**Comment by Flaburgan** [comment]
Let's make it work first and then when 0.6 will be ready and will not change I will help you to integrate it in the design ;)

**Comment by Zauberstuhl** [comment]
@Flaburgan why isn't it working for you?

**Comment by svbergerem** [comment]
In 0.5.x.x the border is associated with the stream and thus will use the full height in most cases. This is also what the white theme currently does. Since the chat also breaks the other themes I think we should have something that fixes it for all themes at the same time.

> This is also the same design like in the profile view and SPV.

With the default theme the borders next to the main stream also look different from those in the profile and the SPV. I guess we'll need a plan how to unify that for all themes.

**Comment by svbergerem** [comment]
Superseded by #6535.

**Pull request closed without merging**
