### PR TITLE
Issue #6145: Fixed position of Tom on the 404-Page

### PR DESCRIPTION
**Pull request by Haidy777**
Just one small addition to set the height of html and body to 100%
Testet it with several browsers, didn't notice that it would break anything.

### CODE REVIEW

**Comment by goobertron** [comment]
Thanks a lot for contributing to Diaspora, it's good to have you on board!

It looks to me as though you can replace `max-height:100%` with `height:100%` rather than adding the second, as `height:100%` should imply `max-height:100%`. But do test to make sure this is OK.

**Comment by goobertron** [comment]
Quickly also, does `height:100%` need to be set for both `html` and `body`? If not, that element could be deleted and `height:100%`  added to the `body` element below. Again, won't have time to test this myself, so it's just a suggestion by looking at that file.

**Comment by Haidy777** [comment]
Body might not be absolutely necessary, but html is.
The main Problem is, that the 'html'-Tag is not big enough.

Body is 100% of the height, but html is not. Because of that Tom is rendered in a space that can't be displayed because it lacks of height.

(Apologies my English, I didn't speak it for a while now and so I got a bit rusty. ;) )

**Comment by goobertron** [comment]
You English is fine! I understand you perfectly. Thank you for explaining that, it makes complete sense.

**Comment by denschub** [comment]
Merged as 990c678cd3a9cc529230cc417f49d2ac874b6324, thak you very much!

Also, goob: 

> You English is fine! 

*Your. (Sorry.)

**Comment by denschub** [comment]
Yikes. Holdon, I had to back this out. I missed that the change was applied globally. No idea how that happened, I am very sorry.

@Haidy777 Please only change the height for `body#error_404` and not globally... :)

**Comment by Haidy777** [comment]
@denschub If you look here: https://github.com/diaspora/diaspora/blob/develop/app/assets/stylesheets/error_pages.scss#L29 you will see that the height of body#error_404 is already set to 100%.
As I explained above, changing the height of body might not be necessary. (Because it is already set to 100%) The problem is that the html-Tag isn't high enough.

To explain what I mean, here are some images:
bildschirmfoto 2015-07-07 um 10 20 20
This is the Version with the current CSS. As you can see, body is the full height of my screen.
bildschirmfoto 2015-07-07 um 10 22 25
In the second you can see the width and height of html in the current CSS.
bildschirmfoto 2015-07-07 um 10 24 50
In picture three you see Tom again with only the value of html's height changed.

Hopefully that helps to understand the problem behind that bug.
Adding the height to html only (above this lines: https://github.com/diaspora/diaspora/blob/develop/app/assets/stylesheets/new_styles/_base.scss#L1-L5) would also work, then the change would only affect all html-Tags. (Which again shouldn't be bad, because max-height is already set)

**Comment by jhass** [comment]
Superseded by #6226 

Thanks!

**Pull request closed without merging**
