### PR TITLE
fix minor errors in db:seed task

### PR DESCRIPTION
**Pull request by Raven24**
someone at rossconf stumbled over the broken seed db task, so here is a fix for it ;)

### CODE REVIEW

**Comment by jhass** [comment]
What do you think about just dropping the seeds file?

**Comment by Raven24** [comment]
I wouldn't be very sad for long  :D

**Comment by jhass** [comment]
Let's do that then

**Comment by Raven24** [comment]
updated PR, not sure how to satisfy hound correctly in this case

**Comment by jhass** [comment]
It's set to table style:
```ruby
{
  a:   b,
  cc:  d,
  eee: f
}

**Comment by Raven24** [comment]
got it, updated.

**Comment by jhass** [comment]
Thanks!

**Pull request merged**
