### PR TITLE
Update in-app Help section

### PR DESCRIPTION
**Pull request by goobertron**
Here's a first iteration to update the in-app Help section. I have included all the new features and UI changes I could think of.

Please check through and make sure everything is covered, and let me know of any further changes required.

The first commit of this PR has already been cherry-picked and merged. @jhass Hopefully pushing the further commit to the same branch hasn't messed things up.

### CODE REVIEW

**Comment by jhass** [comment]
No worries, I'll figure it out ;)

**Comment by Flaburgan** [comment]
Yeah I'll have a look this evening.

**Comment by goobertron** [comment]
Anything I've missed, @Flaburgan? It would be good to get this merged asap so hopefully the updates can be translated to many other languages before 0.5.0.0 is released.

**Comment by Flaburgan** [comment]
Checking it right now. I spotted a few errors (mainly the profile page, no more contacts tiles but a tab, things like that). I'm working on a PR for your PR ;)

**Comment by goobertron** [comment]
Thanks - I'll pick through your changes.

**Comment by Flaburgan** [comment]
I based my PR on your work, you can just pull my changes (click merge pull request) they will automatically appear there :)

**Comment by goobertron** [comment]
What I meant is that I've got to decide whether I wish to incorporate each of your changes before merging anything.

**Comment by goobertron** [comment]
Unh. I'm hoping that this is a random failure causing all the subsequent errors. It looks like it, and `features/desktop/oembed.feature` runs fine locally.

@jhass once this has passed Travis, would you be happy to merge it *unless* I have introduced any factual errors into the Help section? Even if not absolutely everything in that section has been updated, it would be better to include a more up-to-date Help section with fewer errors in 0.5! And if there was times for these updates to be translated before release, that would be excellent.

**Comment by jhass** [comment]
Merged as a75ec75ec7ecd7b141c265c586adf955bd03d2a8

Thank you!

**Comment by goobertron** [comment]
Thank you back!

**Comment by Flaburgan** [comment]
Nice! I'll see if I can still find some improvements.

**Pull request closed without merging**
