### PR TITLE
Update for sq translation

### PR DESCRIPTION
**Pull request by ujdhesa**
Hello,

Here’s an updated translation for sq. Please include it in the new release.

### CODE REVIEW

**Comment by jhass** [comment]
Thank you!

Unfortunately this doesn't cleanly merge, did you perhaps base your edits on old versions of these files?

**Comment by ujdhesa** [comment]
Hello,

and thank you for helping.

I think so. I checked the old sq files against the current en ones (from a fresh clone of diaspora), side by side, using Meld, patching the missing bits. Then translated. Then checked the new translation files with yml-checker.rb. And they passed the check. 

I tried to have a look at the `Resolve conflicts` above but wasn’t able to guess what’s wrong from the output of that button.

**Comment by jhass** [comment]
Make sure you have a clean local git clone of the upstream develop branch, then copy your changed files into this, commit and force push to your GitHub branch

**Comment by ujdhesa** [comment]
Let me delete the fork and recreate it and try again.

**Pull request closed without merging**
