### PR TITLE
Replace jquery.autocomplete with typeahead.js

### PR DESCRIPTION
**Pull request by svbergerem**
Some tests are still missing. This PR replaces jquery.autocomplete with typeahead.js and adds contacts to the search suggestions, even if they aren't searchable. (#4789) This PR **doesn't** add those contacts to the search page itself.

### CODE REVIEW

**Comment by AugierLe42e** [comment]
Nice! Thanks for doing this \o/

**Comment by svbergerem** [comment]
This PR should be ready to review.

**Comment by jhass** [comment]
Thank you!

**Comment by AugierLe42e** [comment]
Can't [autoSuggest.js](https://github.com/diaspora/diaspora/blob/develop/vendor/assets/javascripts/jquery.autoSuggest.custom.js) be replaced too?

**Pull request merged**
