### PR TITLE
Use entypo for control icons

### PR DESCRIPTION
**Pull request by svbergerem**
We already use them in the SPV and this PR unifies the icons.
entypo icons
These icons are:
- cross: for hiding posts, photos or conversations
- trash: for deleting posts, photos, comments or conversations (if you are the last participant)
- bell: notifications / participation
- block: ignore user
- megaphone: report post, photo or comment

Here is a post with the new post control icons:
post with icons

Bootstrap already has a `.controls` class so I called this one `.control-icons`.

I removed `_landing.scss` because I wasn't able to find `landing` anywhere else in our codebase. (And I found it because of the `.controls` in line 24)

### CODE REVIEW

**Comment by Flaburgan** [comment]
Not sure about the megaphone, the exclamation mark is quite good imo.

**Comment by svbergerem** [comment]
I don't like the current situation with the exclamation mark. It is too thin and because of that hard to recognize. Another possible icon would be `warning`:
warning

**Comment by AugierLe42e** [comment]
I like the warning icon.

**Comment by SansPseudoFix** [comment]
I think exclamation triangle is more explicit.
But not sure about blocking icon. What about silhouette with cross?

**Comment by AugierLe42e** [comment]
@SansPseudoFix : The icon doesn't exist crossed.

**Comment by svbergerem** [comment]
@SansPseudoFix We already use the block icon on the profile page.

**Comment by Flaburgan** [comment]
The triangle is way better :)

**Comment by SansPseudoFix** [comment]
@svbergerem I know, but imo, a user-crossed icon is more explicit (but it's not the point here :) ).

**Comment by svbergerem** [comment]
This PR now uses the `warning` icon.

**Comment by svbergerem** [comment]
Green Travis. :)

**Comment by goobertron** [comment]
Exclamation mark in triangle works for me too. Thanks, Steffen.

**Comment by AugierLe42e** [comment]
@svbergerem : Don't you think that [this block](https://github.com/svbergerem/diaspora/blob/entypo-controls/app/assets/templates/stream-element_tpl.jst.hbs) should just be a partial render of [this template](https://github.com/svbergerem/diaspora/blob/entypo-controls/app/assets/templates/single-post-viewer/single-post-moderation_tpl.jst.hbs) ?

**Comment by svbergerem** [comment]
@AugierLe42e Not without a proper refactor which won't be part of this PR.

**Comment by AugierLe42e** [comment]
Ok, I'm willing to do it if you can guide me.

**Comment by jhass** [comment]
Well, let's try this I guess.

Thanks!

**Pull request merged**
