### PR TITLE
Updated translations: de, de-moo, de_formal

### PR DESCRIPTION
**Pull request by spixi**

### CODE REVIEW

**Comment by goobertron** [comment]
See https://webtranslateit.com/en/projects/3020-Diaspora/ for how to contribute translations.

**Comment by spixi** [comment]
Sorry, but what did I break that I got

```
I18n::InvalidLocaleData: can not load translations from /home/travis/build/diaspora/diaspora/config/locales/diaspora/de_formal.yml: #<Psych::SyntaxError: (/home/travis/build/diaspora/diaspora/config/locales/diaspora/de_formal.yml): did not find expected key while parsing a block mapping at line 523 column 7>
```

**Comment by spixi** [comment]
Thank you @goobertron for the link. I will have a closer look, but I have the strong feeling that that web frontend is much less comfortable than Vim, isn’t it?

**Comment by goobertron** [comment]
Maybe so, but translations for most languages/locales must be submitted via WebTranslateIt.

**Pull request closed without merging**
