### PR TITLE
typo in the French translation

### PR DESCRIPTION
**Pull request by trebmuh**
Hope that helps.

PS: I didn't mean to change the last line (n°326) and it looks like the github interface did it automatically. Let me know if it's a mistake and need to be changed back.

### CODE REVIEW

**Comment by SuperTux88** [comment]
Thanks for your contribution, but we use WebTranslateIt for the translations, see: https://wiki.diasporafoundation.org/Contribute_translations

Please fix this typo there.

**Comment by trebmuh** [comment]
@SuperTux88 : thanks for your quick answer.

That said, I'm not going to subscribe to webtranslateit for one typo fix. Please (anyone with a webtranslateit account), feel free to take this typo fix and submit it on your name.

**Comment by Flaburgan** [comment]
Done, thank you.

**Comment by trebmuh** [comment]
Super, merci.

**Pull request closed without merging**
