### PR TITLE
Add closing tags to replace invalid self-closing tags

### PR DESCRIPTION
**Pull request by Flaburgan**
Extracting that commit by @pravi from https://github.com/diaspora/diaspora/pull/8159 to see if CI is green with only this one.

### CODE REVIEW

**Comment by Flaburgan** [comment]
Only one failure, with mysql. I was able to relaunch job with Travis, is this not possible with github actions, or don't I have the necessary rights @jhass @SuperTux88 ?

**Comment by tclaus** [comment]
LGFM

**Comment by Flaburgan** [comment]
Yay, CI is green. I don't know who relaunched the job but thanks. So, as this is quite simple and solving a bug, I'm going to target the next minor release for this PR.

**Comment by SuperTux88** [comment]
Merged as 92a096f03cf0612d05696954ca162da219091950

Thanks for the fix @pravi and @Flaburgan :cookie: and thanks for the review @tclaus :cookie:

**Pull request closed without merging**
