### PR TITLE
Close gallery on outside click

### PR DESCRIPTION
**Pull request by ghost**
Solves #6444

### CODE REVIEW

**Comment by AugierLe42e** [comment]
The second commit let the gallery display the original photo instead of the thumb large.

**Comment by AugierLe42e** [comment]
This is ready to merge.

**Comment by svbergerem** [comment]
I'm not sure about your second commit. The file size of the original image could be a few MB.

**Comment by AugierLe42e** [comment]
On most pods, though, it'll be limited in size, like, for instance to 4MB on d-fr. I don't think this is really a big problem since it only affects desktop version.

**Comment by jhass** [comment]
Please just stop sneaking potentially controverse changes into otherwise unrelated PRs, you're harming yourself.

**Comment by AugierLe42e** [comment]
I think you're misinterpreting me, @jhass. If I wanted to "sneak" something, I couldn't be doing worse than in a such tiny PR. It's a bit ridiculous saying that. I sincerely didn't think that could be any controversial (and I highly regret there are so many controversial things). But if that's what you want, I open a separate PR. It has zero cost for me.

**Comment by svbergerem** [comment]
Thanks! :)

**Pull request merged**
