### PR TITLE
Replace dandelion.jpg with a public domain photo

### PR DESCRIPTION
**Pull request by skyschub**
The original `dandelion.jpg` seems to be released under a non-free license now, and I can't find any proof for that ever being CC, so we probably should replace it. This was inspired by #7972, and although we don't really care about external packaging efforts, this issue made me realize we technically violated the CC license with our old image, because credits were not shown anywhere on the individual installations, but only in our repo, which isn't enough. Shame on us. :)

The image used in this PR [is public domain](https://pixabay.com/en/dandelion-sky-flower-nature-seeds-463928/), and while it's not as pretty as the old one, its the closest I can find because the placement needs a somewhat silent background, as we place text on it. This is how it looks in context:

screen shot 2019-02-02 at 14 08 42

### CODE REVIEW

**Comment by goobertron** [comment]
Thanks for doing this.

How about this image? Released under CC0. If it were mirrored, with the dandelion head on the right as I've done here, would it work on the page? It looks as though the 'Welcome to diaspora\*' text has a slight shadow, so hopefully the light patches wouldn't render the text hard to read.

CC0 dandelion image from dreamstime.com

The image is 4242px wide, so would allow for cropping if necessary. Link at https://www.dreamstime.com/dandelion-blowing-wind-public-domain-image-free-83023111

**Comment by denschub** [comment]
Due to the framing of this PR, we'll never get the entire flower in the frame, but I actually really like the way this looks:

screen shot 2019-02-03 at 08 11 56

Thanks for the suggestion, @goobertron. PR updated.

**Review by utkarsh2102 — COMMENTED** [review]
Loved it. 
Amazing work, @denschub! :heart:

**Comment by utkarsh2102** [comment]
@SuperTux88 @jhass @goobertron @Flaburgan, any updates on this?

**Comment by goobertron** [comment]
@utkarsh2102 the next minor release is due on 17 February, and this PR should be included in that release.

**Comment by utkarsh2102** [comment]
@goobertron, thank you so much!
Looking forward to the next release.

**Review by SuperTux88 — APPROVED** [review]

**Comment by SuperTux88** [comment]
Merged as e47d0d9675868835b0c274f35fc9212379b239b1

Thank you @denschub for the PR :cookie: and @goobertron for the new image :cookie:

**Pull request closed without merging**
