### PR TITLE
account_deletions get stuck while selecting participations

### PR DESCRIPTION
**Pull request by ghost**
Following query takes over 20 minutes and fills up the database:
SELECT \* FROM participations WHERE author_id = XXXXX

On servers with a huge participations-table this is a serious
performance issue which is easily fixed by the author_id index

@SuperTux88 thanks for your help on this

### CODE REVIEW

**Comment by denschub** [comment]
Thank you!

**Comment by Flaburgan** [comment]
Can this be backported to the stable branch?

**Comment by Zauberstuhl** [comment]
that was already asked on IRC. In short no, but you can add the index manually if you insert the migration version into the schema_migration-table. Then you can be certain that it will not result in any db:migration issues in future

**Comment by SuperTux88** [comment]
I simply `cherry-pick`ed this commit, so I have the migration and didn't need to edit the `schema_migration` table by hand. Every podmin can do the same, if he wants this on his pod, but we don't want big (long running) migrations in stable.

**Comment by Flaburgan** [comment]
As long as it doesn't require any manual actions, I don't see the running time as a problem, but as you want.

**Comment by denschub** [comment]
> Triggers to disqualify stuff to be included:
> 
> [...]
> 
> * Stuff that requires long migrations.

([src](https://www.loomio.org/d/mq6HoprD/fixed-schedule-for-bugfix-releases))

**Comment by SuperTux88** [comment]
I'm not sure what an "average sized pod" is, the migration took 32s on my pod, which is below 5 minutes. So I don't know if I'm "average sized"?

**Comment by denschub** [comment]
Fine, you win. Backported as a3ac1e3072293ab5ce5efcda214019a9daffc04e.

**Pull request merged**
