### PR TITLE
Update listen configuration

### PR DESCRIPTION
**Pull request by jhass**
- Drop deprecated port setting
- Listen to unix socket by default

### CODE REVIEW

**Comment by denschub** [comment]
Did you check for any outdated documentation in the wiki?

**Comment by jhass** [comment]
Nope, I'll just update it as people complain ;P

**Comment by denschub** [comment]
Sounds good. Thanks for your PR!

**Comment by Flaburgan** [comment]
Does that imply any manual change if the default setting was not modified? Looks like not, but I want to be sure.

**Comment by jhass** [comment]
Yes it does, the develop branch in production mode will no longer listen to port 3000 anymore by default, but to `tmp/diaspora.sock`.

**Pull request merged**
