### PR TITLE
Improve Typeahead's suggestion

### PR DESCRIPTION
**Pull request by ghost**
Search results now can be opened in a new tab and displays contact's hovercard when hovered.

screen shot 2016-10-01 at 09 24 04

### CODE REVIEW

**Comment by AugierLe42e** [comment]
Ready for review.

**Comment by svbergerem** [comment]
+1 for the links, -1 for the hovercards which I find rather annoying.

**Comment by svbergerem** [comment]
This PR fixes  #7021.

**Comment by AugierLe42e** [comment]
> -1 for the hovercards which I find rather annoying

Even on search results?

**Comment by svbergerem** [comment]
Especially on search results.

**Comment by AugierLe42e** [comment]
Ok, I remove it, then.

**Comment by AugierLe42e** [comment]
Done, BTW.

**Comment by svbergerem** [comment]
Looks good to me. Thanks!

**Pull request closed without merging**
