### PR TITLE
Replace where...first with find_by

### LINKED ISSUE #7539: Inefficient api where.first
In post.rb, we can use find_by to replace where.first which will not do the extra order by the primary key.

### PR DESCRIPTION
**Pull request by svbergerem**
Fixes #7539

### CODE REVIEW

**Comment by denschub** [comment]
Besides somewhat ruining `git blame` by touching all these queries, have you found any actual performance gain? Because I tested them, and query times were exactly the same, so I'm a bit hesitant of merging that stuff just because(tm).

**Comment by svbergerem** [comment]
No, I didn't test this. With this PR we omit the unnecessary `ORDER BY` and I think that `find_by` is better readable than `where(...).first`.

**Comment by denschub** [comment]
Okay!

**Review by SuperTux88 — APPROVED** [review]
👍 🍪

**Comment by SuperTux88** [comment]
Merged as 9d2763089d2796deb5a5d2388f0a92d13447761b

Thanks 🍪

**Pull request closed without merging**
