### PR TITLE
Fix for #5483 and #5757 (mobile stream comments)

### PR DESCRIPTION
**Pull request by KentShikama**
Please see https://github.com/diaspora/diaspora/issues/5483#issuecomment-109277476 and https://github.com/diaspora/diaspora/issues/5757#issuecomment-78388350

### CODE REVIEW

**Comment by jhass** [comment]
https://travis-ci.org/diaspora/diaspora/jobs/65673493#L2807

**Comment by theworldbright** [comment]
I'm confused. Travis is giving me the following error:

```
Scenario: sorting the aspects                 # features/desktop/manages_aspects.feature:79

...

Then I should see "Cat People" as 2. aspect # features/step_definitions/aspects_steps.rb:132
      expected to find text "Cat People" in "0 People" (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/aspects_steps.rb:133:in `/^I should see "([^"]*)" as (\d+). aspect$/'
      features/desktop/manages_aspects.feature:86:in `Then I should see "Cat People" as 2. aspect'
```

So I ran `bin/cucumber features/desktop/manages_aspects.feature` on my localhost and all the tests pass as follows:

```
  Scenario: sorting the aspects                 # features/desktop/manages_aspects.feature:79
    Given I am signed in                        # features/step_definitions/session_steps.rb:1
    And I have an aspect called "People"        # features/step_definitions/user_steps.rb:64
    And I have an aspect called "Cat People"    # features/step_definitions/user_steps.rb:64
    When I am on the contacts page              # features/step_definitions/web_steps.rb:22
    And I drag "Cat People" up 40 pixels        # features/step_definitions/aspects_steps.rb:91
    And I go to the contacts page               # features/step_definitions/web_steps.rb:26
    Then I should see "Cat People" as 2. aspect # features/step_definitions/aspects_steps.rb:132
    And I should see "People" as 3. aspect      # features/step_definitions/aspects_steps.rb:132

9 scenarios (9 passed)
63 steps (63 passed)
```
Am I running the wrong test?

Moreover, I only touched files relating to the mobile view so I'm confused how I'm getting an error on a test related to the desktop view.

**Comment by theworldbright** [comment]
I'll try a rebase.

**Comment by jhass** [comment]
Oh, don't worry, that's one of our randomly failing tests still :/

**Comment by jhass** [comment]
Any chance you could squash the style fixes into their respective commits?

```bash
git remote add upstream https://github.com/diaspora/diaspora.git
git fetch upstream
git checkout 5483-fix-mobile-stream-comments
git rebase -i upstream/develop
# You can move commits around and choose squash
git push -f origin 5483-fix-mobile-stream-comments
```

**Comment by theworldbright** [comment]
Just checking but by "style fixes" you mean commits that affect only how elements look right? Or does it also include code refactoring that doesn't change any behavior?

**Comment by jhass** [comment]
Uh, I meant code style fixes.

**Comment by theworldbright** [comment]
Got it. I squashed this PR into 3 commits: one for each issue and one that is purely design/decoration changes.

**Comment by jhass** [comment]
Great!

**Comment by theworldbright** [comment]
Did my changes cause the following?

```
features/step_definitions/custom_web_steps.rb:63
    When I click the publisher and post "http://mytube.com/watch?v=M3r2XDceM6A&format=json"       # features/step_definitions/posts_steps.rb:62
      Unable to find css "#main_stream" (Capybara::ElementNotFound)
```

**Comment by jhass** [comment]
No that's one of our random failures.

**Comment by denschub** [comment]
This is quite painful to backport and since this is no big issue, I decided not to but that into the next minor.

**Pull request merged**
