### PR TITLE
[WIP] OpenGraph link preview when post previewing

### PR DESCRIPTION
**Pull request by ghost**
This is an attempt to add OG link previewing to post preview in publisher.

### CODE REVIEW

**Comment by jhass** [comment]
You wrote the library? It probably should have some Jasmine tests. You can find quite comprehensive fixture data at https://github.com/jhass/open_graph_reader/tree/master/spec/fixtures

I think I'd also love to see this as a separate project, exposed as Bower package, so we can keep the tests and in particular the fixture data outside the diaspora repo.

**Comment by AugierLe42e** [comment]
I wrote it based on [bootstrap-link-preview](https://github.com/Ekito/bootstrap-linkpreview) (I know I forgot license mention in my commmit).

Ok for the Bower package.

**Comment by AugierLe42e** [comment]
I setup a repo for this [here](https://github.com/AugierLe42e/jquery.opengraph-preview.git). Is it possible for the repo to be integrated to diaspora so that I can be reviewed when developing?

**Comment by denschub** [comment]
A link in this PR is enough I guess. This can be used as a more general library and is not limited to diaspora.

**Comment by denschub** [comment]
So... how's stuff going?

**Comment by AugierLe42e** [comment]
While working on #6551, I noticed that front-end [has already everything needed](https://github.com/diaspora/diaspora/pull/6551/files#diff-b3b0f345d4379fc5bd81a1f9245fe526R25) to display an OG previewing, so we don't actually need to develop a library. Something like [jquery.ogp.js](https://github.com/fiann/jquery.ogp/blob/master/src/jquery.ogp.js) could be sufficient.

**Pull request closed without merging**
