### PR TITLE
Hebrew (he) locale files

### PR DESCRIPTION
**Pull request by yuvadm**
Hey there!

I created basic locale files for the Hebrew (he) locale.
This is an initial work as I plan on starting to hack a RTL version for Diaspora.

Let me know if you have any questions or if I can assist on any RTL or i18n issues.

Cheers!
- Yuval

### CODE REVIEW

**Comment by GreenLunar** [comment]
May I ask why on earth the string are translated into nouns or adverbs and OUT OF CONTEXT???

```
signed_up: "התחברת בהצלחה, אם הדבר מאופשר, יתקבל אימייל אישור בקרוב.."
```
Which says: Connectivity in success, if the thing is enabled, will received confirmation email soon

??? !!!

**Comment by jhass** [comment]
@GreenLunar Please see https://wiki.diasporafoundation.org/Contribute_translations for how to collaborate on the translation, thanks!

**Comment by GreenLunar** [comment]
@jhass I have seen this page, thank you.  It will not be effective to just send a modified and, what I think, is a proper translation, because I will probably have a fight with some "translators" who do what they do, translating verbs into adverbs or nouns, to spew their contact details for reference in CV for Job Application.

They say they do it for having in-discrimination, and that argument was nullified over and over again.  See http://lists.claws-mail.org/pipermail/translators/2014-November/000309.html

I want @yuvadm to explain why the translation is so corrupted?

(I will delete this line to not promote Facebook) Even Facebook has English -> Hebrew translated to verb -> verb! (I will delete this line to not promote Facebook)

**Comment by jhass** [comment]
@GreenLunar It doesn't look like they're part of the current translation team: https://webtranslateit.com/en/projects/3020-Diaspora/people

Here you can see the most active translators: https://webtranslateit.com/en/projects/3020-Diaspora/top_translators?locale=he

Please discuss this at https://webtranslateit.com/en/projects/3020-Diaspora/discussions

**Pull request closed without merging**
