### PR TITLE
Use the full bind path instead of the url

### PR DESCRIPTION
**Pull request by ghost**
In case your domain is different to the configured one
you will run into cross domain issues.

e.g. if you have an onion address you'll have problems with cross-domain
and more importantly sending traffic to the clear web.

### CODE REVIEW

**Comment by jhass** [comment]
Perhaps we can simplify the configuration story there a bit? https://github.com/diaspora/diaspora/blob/9aaf58de120e98d1a6ada24718fc3ffc411a5f0b/config/diaspora.yml.example#L235 seems outdated anyway. Can we drop the `proxy` and `port` setting and just do something like

```rb
bind = AppConfig.url_to bind if  bind.start_with? "/"
bind
```

?

**Comment by Zauberstuhl** [comment]
> Can we drop the proxy and port setting and just do something like

Forcing the podmin to configure his webserver? why not
The only downside would be that a podmin has to manually change the prosody-config if he wants to set a different port (in respect of the prosody wrapper). But I can live with that

also you might have some more work if you want to test jsxc in development mode.

**Comment by jhass** [comment]
Well with this `https://xmpp.example.org:5280/bind` would be a valid value for `bind` anyway, no?

**Comment by Zauberstuhl** [comment]
mh you're right.. classic .. too much normalization

**Comment by Flaburgan** [comment]
So what do we want to do with this?

**Comment by SuperTux88** [comment]
The chat was removed with #8069, this is obsolete now.

**Pull request closed without merging**
