### PR TITLE
[WIP] Comment submission canceled after timeout

### LINKED ISSUE #5566: [Mobile] Sending PM, posts or comments when no network should fail
Currently, when sending a long message with unstable network, the message stays blocked infinitly. There is no way to copy it or edit it again and it is never transmitted. This requires to reload the page and write the comment again.

On mobile version, there should be an uptime for each transmission. If the message cannot be send until then, the UI should display a warning and come back to the edition of the message.

### PR DESCRIPTION
**Pull request by ghost**
Seriously, why do I keep hurting myself this way... >.<
(Tries to) fix #5566.

### CODE REVIEW

**Comment by jhass** [comment]
I don't follow... What does this fix?

**Comment by AugierLe42e** [comment]
It tries to fix #5566.

**Comment by jhass** [comment]
ah, 1 is a bit short though, no?

**Comment by AugierLe42e** [comment]
It's for test purposes but it fails. Need help (like always, it seems).

**Pull request closed without merging**
