### PR TITLE
Cleanup StatusMessage

### PR DESCRIPTION
**Pull request by SuperTux88**
- remove `raw_message` alias and use `text` directly
- do `presence_of_content` validation also for remote posts
- remove `absence_of_content`, because that didn't do anything ...

### CODE REVIEW

**Comment by jhass** [comment]
Thank you!

**Comment by cmrd-senya** [comment]
I'm sorry, but that's not quite fair. I have #6805 finished three months ago and this PR is the second time someone merges PR that introduces changes that makes my PR conflicting with the base branch. The previous was #6902.

What is the reason to merge this one before my PR? Why do I have to continously rebasing my changes without being reviewed?

**Comment by jhass** [comment]
@denschub added the milestone to #6805, so I thought he's going to review it.

**Comment by denschub** [comment]
Uh. I was planning the future with senya, and to clarify which tasks should get prioritized for 0.6.0.0, I've assigned the milestone. That's all. Also, I see there were commits after I assigned the milestone, so I am not even sure if this is ready to merge? 😕

**Comment by cmrd-senya** [comment]
It was in conflict state when you assigned the milestone, so I rebased it. And then I rebased it once more after this merge. That's why there are commits after the milestone. Also I added https://github.com/diaspora/diaspora/pull/6805/commits/035a483a7af669607ceb9a33a9f7e754d70ee635 commit because I discovered an issue similar to #6913 and fixed it along the way.

It must be ready for the review.

Please, if there are some conflicting PRs and no special reason to merge some code first, could you at least give me review before merging the conflicting request? Or merge mine if it's ready. I realize also that there are too many open PRs and it's probably hard to track conflicts. I'll try to help with ophan sorting/adoption then.

**Pull request merged**
