### PR TITLE
Don't truncate notification emails anymore

### LINKED ISSUE #4342: email notifications should contain full content for public posts
When I receive a notification of someone mentioning me or answering on my post, I want to read the full thing. I don't wat to receive a cut-off message and get frustrated mid-sentence, when the excerpt of the notification-mail ends and I have to remember where I was and search for this place on D* and read on.

I want to fully read the interaction people have with me and then go to the thread (post with comments) and answer.

A wet dream of me would be to be able to answer to comments via email, but that will have to wait, I think. :)

But please, remove the shortening.

### PR DESCRIPTION
**Pull request by Flaburgan**
Close https://github.com/diaspora/diaspora/issues/4342

### CODE REVIEW

**Comment by svbergerem** [comment]
Looks good to me. It would be great if someone with more RoR knowledge could review and merge this PR.

**Comment by jaywink** [comment]
Looks good from here too. If no one opposes, after a rebase and commit squash IMHO can merge.

**Comment by Flaburgan** [comment]
Rebased.

**Comment by jaywink** [comment]
Doh, it's, again, out of sync :P A new rebase, sorry :) Also, could you squash the two commits to one? Will then merge asap before another commit gets in the way.

**Comment by Flaburgan** [comment]
Done ;)

**Comment by jaywink** [comment]
Mergy mergy, thanks @Flaburgan !

**Pull request merged**
