### PR TITLE
CSS: set "resize: vertical" as default for textarea

### PR DESCRIPTION
**Pull request by korun**
Hi there!

I think we should set default `resize` param to make textareas looks pretty, on the conversations pages, or `/profile/edit`...

### CODE REVIEW

**Comment by Flaburgan** [comment]
Yeah, why not.

More about resize [on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/resize)

**Comment by Flaburgan** [comment]
Don't worry about the CI, it's a random failure.

**Comment by svbergerem** [comment]
For the publisher and the comment textarea we set `resize` to `none` and use [autosize](http://www.jacklmoore.com/autosize/) to automatically change the height based on the input. Maybe this is something we could use for all textareas?

**Comment by korun** [comment]
> Don't worry about the CI, it's a random failure.

Oh, thanks! :)

> For the publisher and the comment textarea we set `resize` to `none` and use [autosize](http://www.jacklmoore.com/autosize/) to automatically change the height based on the input. Maybe this is something we could use for all textareas?

Maybe, but I think that we also need to have a clear default value.

**Comment by svbergerem** [comment]
> Maybe, but I think that we also need to have a clear default value.

This was meant to be a clear default value:

> use for all textareas

`textarea { resize: none; }` and `autosize($("textarea"))` for both desktop and mobile.

**Comment by korun** [comment]
I think `resize: vertical` is provide more functional, for more browsers and versions.

Of course, I can change property to `none` if needed. Should I also add autosize js in this PR?

**Comment by svbergerem** [comment]
Autosize changes the height on input so having `resize: vertical` doesn't sound really useful to me. It might be also confusing when you are able to resize the textarea and with the next character you enter into the textarea it resizes automatically.

But if anyone has some good reasons why we should keep `resize: vertical` that would be also ok for me.

> Should I also add autosize js in this PR?

I think that would be great but maybe wait for a second opinion before changing anything.

**Comment by denschub** [comment]
Actually, I have no issues with `resize: vertical` if it looks okay. Github, for example, is also autosizing their textearas but they still allow the users to resize them vertically. I like that, but I'll not fight for it.

++ to adding the `autosize` library on text areas where it is not active yet.

**Comment by svbergerem** [comment]
Alright, so let's stick with `resize: vertical`. @korun Would you like to add autosize in this PR or should it happen in another one?

**Comment by korun** [comment]
I think autosize will require more checks in different situations, so it is better to add it in a separate PR.

**Comment by svbergerem** [comment]
Thank you! :)

**Comment by korun** [comment]
Thank you all, too)

**Pull request merged**
