### PR TITLE
Refactor available services settings

### LINKED ISSUE #4941: Account settings 'services' tab does not explain how to add services (if none are available?)
Having recently tested out a small public pod, when I click on the 'services' tab in my profile it helpfully told me that I had no services connected, and provided no other information at all.

Expected behavior: tell me I am unable to connect services if that is indeed the case, or provide me a list of services to choose from if I am able to connect some.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1828394-account-settings-services-tab-does-not-explain-how-to-add-services-if-none-are-available?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by svbergerem**
Fixes #4941.

**Before**:
before

**After**:
after

### CODE REVIEW

**Comment by Flaburgan** [comment]
Thanks for dealing with that. The code looks ok to me.

**Comment by goobertron** [comment]
I really like the new presentation. Thanks for this.

**Comment by denschub** [comment]
Thank you!

**Comment by gordon-morehouse** [comment]
Thanks! :)

**Pull request merged**
