### PR TITLE
5041 total user statistic shouldnt include closed accounts

### PR DESCRIPTION
**Pull request by MarcBurt**
I'm new to this, sorry if I've done anything wrong!
Saw this: https://github.com/diaspora/diaspora/issues/5041 and attempted to fix it, put the logic in the model rather than the presenter. 
The query searches for users with a username (to exclude invitations - mentioned in the thread) and Users with closed accounts.

### CODE REVIEW

**Comment by jhass** [comment]
I'd still like this in for the spec, even though the actual fix is already applied. Would you mind rebasing? :)

**Comment by MarcBurt** [comment]
Hi, yes I'll be able to do so.
I won't have access to my dev machine for a while however.

**Comment by jhass** [comment]
I took the liberty to rebase this and refactor it a bit, thanks!

**Comment by Flaburgan** [comment]
I merged that but the total_user count didn't change on https://diaspora-fr.org/statistics.json

**Comment by jhass** [comment]
Yes, the actual change was already included in #5464, I just backported the spec for it from this PR, where the line in #5464 was also taken from.

**Pull request merged**
