### PR TITLE
Create event.svg

### PR DESCRIPTION
**Pull request by teslasmoustache**
It seems that there will some day be an event function. Might as well have an icon for it.

### CODE REVIEW

**Comment by jhass** [comment]
Mh, we're actually trying to much as many icons as possible to Entypo.

**Comment by jhass** [comment]
Oh, and you committed an empty file.

**Comment by teslasmoustache** [comment]
god, yeah, I'm being a dumbass about this.

**Comment by denschub** [comment]
What @jhass said means we're moving away from icon files to a webfont containing all the icons, so adding a seperate SVG is not needed.

Also, even if we would merge this commit because we're not able to find a nice icon in Entypo, your file lacks license information.

**Comment by svbergerem** [comment]
There is a similar Entypo icon.

https://web.archive.org/web/20140912210715/http://entypo.com/characters/
U+1F4C5

**Comment by denschub** [comment]
I'm closing this; we've got an Entypo icon to use as soon as we have a event feature, no reason to add a icon here.

Thanks for your work, though. Please have a look at the other open issues, I'm sure you'll find something nice to do. :)

**Pull request closed without merging**
