### PR TITLE
order-of-comments-on-the-mobile-version-is-reversed #5804

### PR DESCRIPTION
**Pull request by visualsayed**
I'm sorry for causing this issue.

### CODE REVIEW

**Comment by jhass** [comment]
No worries. I wonder though if we can't reuse the `@comments` from the controller as we did earlier? You use `@post`, so the partial is dependent on the controller setting a variable already anyway.

Another nicer solution would be to use a [scope](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_many) on the association I guess.

**Comment by visualsayed** [comment]
let me check this again.

**Comment by visualsayed** [comment]
The Comment model already define for_a_stream scope that returns comments ordered by created_at ASC

**Comment by jhass** [comment]
Thanks!

**Pull request merged**
