### PR TITLE
DRY the NotificationsHelper

### PR DESCRIPTION
**Pull request by cmrd-senya**

### CODE REVIEW

**Comment by denschub** [comment]
> 1 file changed, 24 insertions(+), 24 deletions(-)

Nice optimization there! :smile_cat:

No, really, the only gain we'd get out of this is not having to repeat two attribute assignments, which is not really worth the added complexity by adding another function. I really appreciate your effort, but please don't move code around just to get some PRs for your crowdfunding campaign. I do understand that you want to have stuff to present to your supported, but maybe start at doing the work you initially planned to do...

Sorry. Again, closing this PR since I do not see any profits from merging this.

**Comment by cmrd-senya** [comment]
> No, really, the only gain we'd get out of this is not having to repeat two attribute assignments, which is not really worth the added complexity by adding another function.

I don't agree with you here in terms of the code.

> please don't move code around just to get some PRs for your crowdfunding campaign (at least thats how it looks to me at the moment). I do understand that you want to have stuff to present to your supporters, but maybe start at doing the work you initially planned to do...

That was very evil of you Dennis. This hurted me deeply. I hoped you're not such a hateful wicked person, but apparently, you are.

**Comment by denschub** [comment]
> I don't agree with you here in terms of the code.

Great, then maybe share some insights in your plan, but don't open a pull request without any description that has no visible use in the first place. All information I got from you in this PR was the title which claims to remove some code repetitions, which would be a very valid case for refactorings, but there was absolutely nothing repeated besides two very simple function assignments. So, besides moving logic out into a function, adding those two lines you saved by removing the duplicate assignments, there is no gain here. If you have intentions, tell us, since my crystal ball is really vague at showing me your ideas.

> I hoped you're not such a hateful wicked person, but apparently, you are.

Thank you very much! So, how am I wrong? You cited this PR in your latest backer update so it is kinda save to assume you're doing this in your paid time. Which, in my opinion, is the wrong thing. You are very welcome to disagree with me here, but insulting me is a great way to make me everyone incredibly angry.

So, how about being pissed at each other, how's getting back at your very first PR (which is #6726) and address the concerns I raised [23 days ago](https://github.com/diaspora/diaspora/pull/6726/files#r60527394) about the spec you're basing you entire work on being totally incomplete and apparently unmaintained. I am pretty much aware that this is an incredibly boring part of the user backup and restoration project, but I guess we both can agree that it is completely wrong to start basing the entire thing on a data format that's not finished, eh?

So far, I thought that the user migration is indeed your main project and the part you'd spent your time with. If that's not the case, feel free to correct me, please.

**Comment by cmrd-senya** [comment]
You said
> No, really, the only gain we'd get out of this is not having to repeat two attribute assignments, which is not really worth the added complexity by adding another function.

But it doesn't raise complexity. I would say it simplifies the way it looks and the way it works. I consider the repetitions of that kind a bad style and it totally worth eliminating them. Irrelatively of any furhter changes to the code (but I wouldn't touch this if I didn't intent to change it further).

> You are very welcome to disagree with me here, but insulting me is a great way to make me everyone incredibly angry.

There is always a gentle way to state your opinion, but you choose to talk vicious sarcastic things which can't help hurting a person and complaining about me insulting you. I guess there is no way to set up healthy communication if you don't see your behavior is wrong. OK, I can tolerate that at least to the end of my project, please keep the way you are comfortable with.

>So, how about being pissed at each other, how's getting back at your very first PR (which is #6726) and address the concerns I raised 23 days ago about the spec you're basing you entire work on being totally incomplete and apparently unmaintained. I am pretty much aware that this is an incredibly boring part of the user backup and restoration project, but I guess we both can agree that it is completely wrong to start basing the entire thing on a data format that's not finished, eh?

In the plan I shared before in my backers updates I stated that first I'm implementing the account migration rename case, which doesn't require archive import. And no job is base on the account import so far. There is a https://github.com/diaspora/diaspora/pull/6750 and I consider this has to be merged first and only after it is relevant to add archive import functionality, so the PR about archive format is quite a low priority now, I can postpone it for a couple of weeks. Moreover, #6726 depends on the loomio voting which was initiated by your hint and is not finished yet. Things which are more important for the migration project at the moment are not getting reviewed, so I switched to the #1851 which is another task I have to complete as a stretch goal. This all has been said in my backers updates which you're aware of. In the last one I also said that I will switch to the #6726  the next week so there was no need for you to pointing me.

**Pull request closed without merging**
