### PR TITLE
Fix page width on people view (BS3 regression)

### PR DESCRIPTION
**Pull request by ghost**
People page regains its normal width.
Before:

capture d ecran 2015-07-24 a 20 35 59

After:

capture d ecran 2015-07-24 a 20 33 42

### CODE REVIEW

**Comment by svbergerem** [comment]
http://stackoverflow.com/a/18882813

We use the Bootstrap grid system also on other mobile pages (e.g. on those pages where we have one combined template for the mobile and desktop view) so I'd suggest that we start using the Bootstrap grid in a proper way instead of removing it from some pages and keeping it on others.

**Comment by AugierLe42e** [comment]
https://github.com/diaspora/diaspora/pull/6074/files#diff-9eac80d828cb5c27b2a4ae46132e070fL5

**Comment by svbergerem** [comment]
On the people show page [that stream is already wrapped](https://github.com/diaspora/diaspora/blob/develop/app/views/people/show.mobile.haml#L25) in a `.col-md-12` and having a `.col-**-**` inside a `.col-**-**` without a `.row` in between is wrong,  but there are some other places where this is missing which means that it is inconsistent, that's right.

**Comment by AugierLe42e** [comment]
So basically, a `.row` is missing? Ok, let me correct that.

**Comment by svbergerem** [comment]
One way to make that consistent throughout our codebase would be a rule like
> 1. Whenever you use `col-**-**`, wrap it in a `.row` in the same file. 
> 2. Whenever you render some file in a `.row` make sure there is a `.col-**-**` in between.

**Comment by svbergerem** [comment]
> So basically, a .row is missing?

It's not just the `.row`. The structure of our code should be

```haml
.container # (or .container-fluid) should be somewhere in the layout files
  .row
    .col-**-**
      .row
        .col-**-**
  .row
    .col-**-**
```

**Comment by AugierLe42e** [comment]
I don't think there is any `.container` anywhere on the mobile view. At least, I don't find any on stream page.

**Comment by Flaburgan** [comment]
I noticed this problem today, thank you for solving it :)

**Comment by svbergerem** [comment]
Thanks! As I wrote in [this comment](https://github.com/diaspora/diaspora/pull/6247#issuecomment-124620276) I think we should properly use the Bootstrap grid on the mobile website but that is out of scope of this PR.

**Pull request merged**
