### PR TITLE
Replace %{third_party_tools} by the appropriate hyperlink in tags FAQ 

### PR DESCRIPTION
**Pull request by flamontagne**
It's my first contribution to diasopra. It's rather small but it's a start :) Let me know if there is something I forgot to do.

Thank you

### CODE REVIEW

**Comment by svbergerem** [comment]
It looks like this breaks https://github.com/diaspora/diaspora/blob/develop/spec/javascripts/app/views/help_view_spec.js#L75

**Comment by svbergerem** [comment]
Apart from the failing spec this PR looks good to me. You just need to change https://github.com/diaspora/diaspora/blob/develop/spec/javascripts/app/views/help_view_spec.js#L77 (compare it to https://github.com/diaspora/diaspora/blob/develop/spec/javascripts/app/views/help_view_spec.js#L72). As soon as you fixed that this PR should be ready to merge.

**Comment by flamontagne** [comment]
Ok, thanks. I'w working on it right now.

**Comment by flamontagne** [comment]
Ok the jasmine spec has been fixed. 

PS: I only executed the rspec specs in the previous PR. That's why I didn't notice this jasmine failing test. Sorry about that!

**Comment by svbergerem** [comment]
@flamontagne No problem. Thank you for your contribution! :)

**Pull request merged**
