### PR TITLE
Do not disable submit button if comment is empty in mobile view

### LINKED ISSUE #5485: Mobile: Comment button turns uresponsive when trying to submit an empty comment
Commenting on the mobile view, if you have an empty comment textarea and if you click the Comment button, the button turns unresponsive, saying just ”Commenting...”and staying like that infinitely. Curiously enough, the post that you tried to "comment" appears in your "My activity" stream after this.

I guess the expected behaviour would be to focus on the textarea, just like on the desktop view.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7134012-mobile-comment-button-turns-uresponsive-when-trying-to-submit-an-empty-comment?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by manuelVo**
Fixes #5485

### CODE REVIEW

**Comment by jhass** [comment]
Thanks!

**Comment by AugierLe42e** [comment]
Arg! This has outdated #6509 :'(

**Comment by jhass** [comment]
The scope is sorta hard to grasp, I can't review the JS part of that thoroughly, it's hanging around for a month and it's easy to undo this there.

**Comment by AugierLe42e** [comment]
NP.

**Pull request merged**
