### PR TITLE
Add a notification subscribtion to the single post view

### PR DESCRIPTION
**Pull request by ghost**
notifsubscribtion

### CODE REVIEW

**Comment by Flaburgan** [comment]
Thanks to deal with that! I agree that it's more important to have it in the SPV than in the stream, because when you get a notification and think "Damn, I don't want to know about this stuff anymore", you have a link to the post, but not to the stream. So, it's hard to find it again in your stream, and to be able to shut off (or on) the notification in the SPV is a nice improvement. I would like to see the same icon used on both places though, so if you change it here, you would have to do it in the stream and in the header too.

**Comment by AugierLe42e** [comment]
This part may need a refactor, but too complex for me.

**Comment by jhass** [comment]
> Is it worth to fix Milou's comments ?

Always, not fixing them requires a config change instead.

**Comment by AugierLe42e** [comment]
Doing it right now so.Someone to help me with [cucumber](https://travis-ci.org/diaspora/diaspora/jobs/53472264#L2108) ?

**Comment by jhass** [comment]
Looks like one of the "random" failures.

**Comment by AugierLe42e** [comment]
Two times the same ? Weird.

**Comment by AugierLe42e** [comment]
Ok it was. So I guess it's ready to merge.

**Comment by AugierLe42e** [comment]
To be continued after #5762 is merged;

**Comment by AugierLe42e** [comment]
Can be merged now.

**Comment by svbergerem** [comment]
Thank you!

**Pull request merged**
