### PR TITLE
Language filter

### PR DESCRIPTION
**Pull request by abhineet-gsoc**
I want to add language filter and currently working on it. Facing some difficulties and as per instructions from jhass gave a pull request for a discussion base. 
1. I am trying to make changes to user getting started page and add language choice to it. I created a table called language through the model . Used the seed command to populate it with relevant entries. However I want to store the languages as tags itself in the form of #language_tag_{language Name} . So I am using tag_following paths. Javascript and languages_controller.rb should help me do that but due to some error the autocomplete part is not working. Please point the error. 
2. When someone wants to post a status they have a language dropdown menu in it similar to aspects. I have created the dropdown button and given relevant options. I have tried to make it exactly look like aspects dropdown . I want the selected value in status_message_controller.rb. Please let me know how to do it.

### CODE REVIEW

**Comment by abimelex** [comment]
is somebody still working on it?

**Comment by balasankarc** [comment]
No comments were given on those last commits. Can someone do that so that we can get other people to build from there? I know the core developers are busy, but still, can you please do that?

**Comment by jhass** [comment]
Tbh it's probably better to start over at this point with a clean design goal.

**Comment by balasankarc** [comment]
Oh. :disappointed:

**Comment by denschub** [comment]
I have to agree with Jonne. This code is both unfinished and not really usable anymore. #3513 exists for this feature, so I guess it's save to close this issue. Thanks to everyone for their work!

**Pull request closed without merging**
