### PR TITLE
Fixed variable drawer width

### PR DESCRIPTION
**Pull request by ghost**
That's the correct way to handle the drawer ;)

### CODE REVIEW

**Comment by svbergerem** [comment]
That doesn't work for browser windows with a width smaller than 400px. I don't know how common that is but I think the mobile version should also work for those resolutions.
320px

**Comment by AugierLe42e** [comment]
Let's say the following, then. I don't think there is any device thiner than 250px. And event then, I don't think we should support them.

**Comment by svbergerem** [comment]
Another idea: Set the drawer width via media query.
max-width: 400px => `$drawer-width: 100%`
else: `$drawer-width: 400px`

Everything else like you did that before. (`transform: translateX(-$drawer-width);`)

**Comment by AugierLe42e** [comment]
Done. `$drawer-width-offset` is to prevent toggle button to be hidden when looking on a 400px screen.

**Comment by svbergerem** [comment]
Thank you!

**Pull request merged**
