### PR TITLE
Indicate proper way to report bugs in sidebar, close #4779

### LINKED ISSUE #4779: Sidebar should indicate proper way to report bugs on github
Now it says "use #bug". It should say to report issues on github. Maybe the whole text should be rewritten in this section.

https://iliketoast.net/posts/183549#23f45ca12300d9f3

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1413416-sidebar-should-indicate-proper-way-to-report-bugs-on-github?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by lislis**
Update the `bug` link in the sidebar to the [report bug wiki page](https://wiki.diasporafoundation.org/How_to_report_a_bug)

I stumbled over this ticket https://github.com/diaspora/diaspora/issues/4779 and thought I could fix it. Let me know if more/ other things are requried

### CODE REVIEW

**Comment by svbergerem** [comment]
Looks good to me! Could you please squash the commits?

By the way: randomly failing tests are nothing you have to care about. We are aware of those  and we check if the failing tests are related to the pull request. We can also rerun some tests if this is important to you or important to us. Just ping us here or on IRC if you think that we should trigger some tests.

**Comment by lislis** [comment]
@svbergerem cool, thanks for the heads up on tests ;)
I just squashed and rebased

**Comment by svbergerem** [comment]
Thank you! :)

**Comment by lislis** [comment]
yay

**Pull request merged**
