### PR TITLE
Fix available services not correctly displayed

### LINKED ISSUE #5589: Wrong information on the new (HTML) statistic page
I can see two types of errors:

- Registrations are shown as opened while they are not
- Services are all "Not available" while they are!

For example, you can compare Diaspora-fr information:

- That's ok on the JSON page: https://diaspora-fr.org/statistics.json
- But not on the HTML page: https://diaspora-fr.org/statistics

Related to https://github.com/diaspora/diaspora/pull/5464

### PR DESCRIPTION
**Pull request by ghost**
This should fix #5589

### CODE REVIEW

**Comment by jhass** [comment]
service is guaranteed to be a symbol, since that array is actually a hardcoded constant. Therefore I'd prefer the helpers to be updated to expect a symbol instead of a string.

**Comment by AugierLe42e** [comment]
Like this ?

**Comment by jhass** [comment]
Yup, thanks!

Btw. your current commit author email is not associated to your github account ;)

**Comment by AugierLe42e** [comment]
This is because I don't want it to be displayed publicly on github.

**Pull request merged**
