### PR TITLE
Updating es ve locale

### PR DESCRIPTION
**Pull request by johand**
adding translations

### CODE REVIEW

**Comment by denschub** [comment]
I'm sorry, but I have to close this as we do not manage our translations via GitHub pull request. Please check https://wiki.diasporafoundation.org/Contribute_translations for information on how to contribute your translations. Thanks for your work! :)

**Comment by johand** [comment]
@denschub the wiki says 

There are two ways you can contribute a translation: **with a pull request** or at WebTranslateIt. But lets start with some general notes first. 

weird, always i sent translations with pull request. regards

**Comment by svbergerem** [comment]
@denschub: 
> Languages handled outside of WebTranslateIt [...] es-VE

**Comment by jhass** [comment]
Yes, es-VE is handled outside.

@johand we switched to a model with two integration branches from which we do releases from, currently `stable` is where our 0.5 release series is branched from while we prepare 0.6 in `develop`. Since you based your PR on `develop` your changes wouldn't be visible until `0.6` is released. We push `stable` to WebTranslateIt to have the most up-to-date translations in each release we do. Maybe you want to reconsider using the service?

**Comment by denschub** [comment]
Bwahaha. I'm sorry. Thanks, @svbergerem.

**Comment by goobertron** [comment]
Don't worry, Dennis - I think I made the same comment last time this language was updated! :)

**Comment by johand** [comment]
@jhass Hello.

i get it, maybe next time i will try the web translator. there is any a chance of create the pull request based on master for the translations via pull request? for me is more comfortable. thank you

**Comment by jhass** [comment]
I don't understand. Git is more comfortable to you but you don't know how to switch branches?

**Comment by johand** [comment]
i know how switch between branches :smile: i always make the pull request based on develop because of the Quickfire Do’s and Don’t’s in https://wiki.diasporafoundation.org/Git_workflow

**Comment by jhass** [comment]
Yes, for regular contributions `develop` is the main integration branch and we decide to backport some stuff to `stable`. But tbh that gets really cumbersome for translation files and has a chance of destroying some of your work.

**Comment by jhass** [comment]
Closing this for now, @johand hope to see a PR based on the `stable` branch soon! Or say a word and we switch it to WebTranslateIt ;)

**Pull request closed without merging**
