### PR TITLE
Refactor and improve sidebar css

### PR DESCRIPTION
**Pull request by svbergerem**
## before - after

leftnavbar
rightbar

### CODE REVIEW

**Comment by jhass** [comment]
Any chance to have some padding to the placeholder in the followed tags input?

**Comment by svbergerem** [comment]
@jhass 
padding tags input

**Comment by jhass** [comment]
Better, but if I'm honest that it's not vertically centered still bugs me.

**Comment by svbergerem** [comment]
tags input

**Comment by Flaburgan** [comment]
Nice! Why did you remove the gray background on the invitation link? This shows that the field can't be modify. What do you think?

**Comment by svbergerem** [comment]
The background was white in the blueprint version and for me the gray background was too distracting. For me input fields with gray backgrounds are part of forms and inform you about a value that will be sent. In this case it is an input field you should interact with by selecting the invitation link.

Maybe an input field isn't even the right element for the invitation link but that shouldn't be part of this PR.

**Comment by jhass** [comment]
Thank you!

**Comment by Flaburgan** [comment]
Hey @svbergerem as you changed the invitation link field design, you should change it in the contact page and the search page too to be consistent.

**Comment by svbergerem** [comment]
@Flaburgan done: #5799.

**Pull request merged**
