### PR TITLE
'toggle mobile' becomes 'Toggle Mobile'

### PR DESCRIPTION
**Pull request by GPhMorin**
For more capitalization consistency.

### CODE REVIEW

**Comment by maliktunga** [comment]
This pull request is too specific. See https://github.com/diaspora/diaspora/issues/5520

**Comment by RichKavanagh** [comment]
You couldn't wait two more days for the Loomio vote to finish?

**Comment by maliktunga** [comment]
@RichKavanagh Even though the voting period is still running, this proposal is too specific to be acceptable. We shouldn't make 200 commits to apply a uniform capitalization.

**Comment by jhass** [comment]
Please, both of you, we don't need to copy paste a discussion to two places.

**Comment by maliktunga** [comment]
@jhass Thank you for the clarification.

**Comment by RichKavanagh** [comment]
> We shouldn't make 200 commits to apply a uniform capitalization.

How many should we make?

**Comment by maliktunga** [comment]
@RichKavanagh Two or three should be enough in my opinion. That depends of how many text strings are forgotten or mistakenly formatted.

**Pull request closed without merging**
