### PR TITLE
[WIP] Fetch user profile on mention if it is unknown

### PR DESCRIPTION
**Pull request by cmrd-senya**
ref #4491

### CODE REVIEW

**Comment by Flaburgan** [comment]
<3

**Comment by cmrd-senya** [comment]
Is the ruby [publisher](https://github.com/diaspora/diaspora/blob/develop/lib/publisher.rb) used anywhere at all? I guess we use the javascript one right now?

**Comment by denschub** [comment]
Could you please not ask random codebase questions in unrelated PRs?

**Comment by cmrd-senya** [comment]
Well, I have failing tests with publisher, so I wouldn't say it's unrelated

**Comment by denschub** [comment]
> Well, I have failing tests with publisher,

And so are [64 other tests](https://travis-ci.org/diaspora/diaspora/jobs/123314316). ;)

**Comment by cmrd-senya** [comment]
Yeah, it was a nice shot

**Comment by jhass** [comment]
Superseded by #6992, thank you for your work!

**Pull request closed without merging**
