### PR TITLE
Remove statistics.json

### PR DESCRIPTION
**Pull request by svbergerem**

### CODE REVIEW

**Comment by Flaburgan** [comment]
Podupti.me and the-federation.info both use nodeInfo, so we should be fine there.
In the last 24h I have GET requests on  `/statistics.json` in my log from https://f.left.social/ https://kirgroup.com/ carina.uberspace.de https://hub.libranet.de and several other friendica and hubzilla pods. I don't know why these nodes need to do that, but this PR is dropping this route so it will soon answer 404. Those are up-to-date servers so I'm warning @annando and @zotlab here.

**Comment by annando** [comment]
Friendica is polling for the statistics.json for its server type detection. The development version now uses nodeinfo as well, but release date will be somewhere in summer, I guess.

We have to poll statistics.json in the future as well since we want to detect different versions of the different systems. But this shouldn't create problems, I guess.

**Comment by SuperTux88** [comment]
@annando so this PR would break federation with friendica? Then I think we should wait.

**Review by SuperTux88 — APPROVED** [review]
Code looks good, but let's wait until friendica doesn't need it anymore.

**Comment by annando** [comment]
It doesn't really break the communication. It's just a small inconvenience. As long as there is a ````X-Diaspora-Version:```` header, the detection will still work.

**Comment by SuperTux88** [comment]
Yes, the `X-Diaspora-Version` header is still there. So nothing breaks? It's just an additional request that result in a 404 and then fallback to another request reading `X-Diaspora-Version`?

**Comment by annando** [comment]
The header probing is done all the time since it is needed for other network systems as well.

**Comment by SuperTux88** [comment]
Ok, then I think we can safely merge it?

**Comment by annando** [comment]
Feel free.

**Comment by SuperTux88** [comment]
Merged, thanks @svbergerem for the work and @annando for the feedback. 👍

**Pull request merged**
