### PR TITLE
[stable] bump jsxc to v0.1.4

### PR DESCRIPTION
**Pull request by ghost**
update jsxc to the latest stable version.

This was tested for stable(alpha) branch!

### CODE REVIEW

**Comment by axilleas** [comment]
@Zauberstuhl I checked out [your branch](https://github.com/librenet/librenet.gr/commits/Zauberstuhl/bump_jsxc) and pushed to our pod, but no fix for chat :/ Also now I cannot even find the `#jsxc_roster` element.

**Comment by Zauberstuhl** [comment]
Hi. yes I think for this we need some rails-assets experts.

The thing is if you run `jsxc.init()` on the JS console the chat will be displayed
BUT an old version of it:
untitled

it should look like [this](https://sechat.org/uploads/images/052f9a529c484a3c6e16.png)

my suggestions would be try running `bundle exec rake assets:clean` or the hard-core method `bundle exec rake tmp:cache:clear; bundle exec rake assets:precompile;`

**Comment by axilleas** [comment]
I actually did a precompile while deploying, did it again (also clearing the cache) and also `jsxc.init()` in the console says:

```
TypeError: jsxc is undefined
```

I see the screenshot is from our pod, I wonder why I can't do this too :/

**Comment by Zauberstuhl** [comment]
mh really strange. but as I said this is something I encountered already and
it has nothing to do with the actual jsxc package.

Try following. it should display version 0.1.4:
```
diaspora@sechat:~/diaspora$ bundle show rails-assets-diaspora_jsxc
/home/diaspora/.rvm/gems/ruby-X.X.X@diaspora/gems/rails-assets-diaspora_jsxc-0.1.4
```

the last I can think of is:
```
bundle exec rake tmp:cache:clear;
bundle exec rake assets:precompile;
```
but that will wipe all your assets. means; depending on your hardware that could take a while
and of course restart the server.

**Comment by axilleas** [comment]
Hmm, seems I have an alpha version
```
/var/www/diaspora/vendor/bundle/ruby/gems/rails-assets-diaspora_jsxc-0.1.4.alpha.1
```

> the last I can think of is:
>
> ```
> bundle exec rake tmp:cache:clear;
> bundle exec rake assets:precompile;
>```
> but that will wipe all your assets. means; depending on your hardware that could take a while
> and of course restart the server.

I did that but saw no difference.

**Comment by Zauberstuhl** [comment]
are you sure you ran `bundle install` ? that should install the stable version 0.1.4 over the alpha version (just tested it).

if that is not the case run `gem uninstall rails-assets-diaspora_jsxc` and uninstall all versions
and hit `bundle install` again (and make sure that bundle tells you he is using 0.1.4 now).

**Comment by axilleas** [comment]
Ok my fault, I was not on your branch... Still the problem persists :/

I now have `/var/www/diaspora/vendor/bundle/ruby/gems/rails-assets-diaspora_jsxc-0.1.4`.

I ran:

1. `bundle install`
1. `bundle exec rake assets:clean`
1. `bundle exec rake tmp:cache:clear`
1. `bundle exec rake assets:precompile`
1. restart unicorn

**Comment by axilleas** [comment]
Ok after a brief chat with Lukas, the problem is with firefox, chromium works as expected.

**Comment by axilleas** [comment]
@Zauberstuhl in firefox I had `media.peerconnection.enabled` to false, toggled to true and I can now see the chat window!

**Comment by Zauberstuhl** [comment]
ah no way.. thanks for sharing!!

**Comment by axilleas** [comment]
Hi, when are you planning to merge this?

**Comment by Zauberstuhl** [comment]
> Hi, when are you planning to merge this?

@svbergerem

**Comment by svbergerem** [comment]
Thank you. :)

**Pull request closed without merging**
