### PR TITLE
Include count in mobile post action link and increase reshare counter after reshare

### PR DESCRIPTION
**Pull request by svbergerem**
This PR moves the post interaction counts into the link and thus increases the size of the links. This makes it easier to like, reshare and comment on posts on mobile devices.

This PR also adds code to increase the reshare counter after resharing a post from the mobile version.

### CODE REVIEW

**Comment by SuperTux88** [comment]
When I click the number for likes, nothing happens (cursor switches to indicate it's a link, but nothing happens on click), but it works for the number of comments and reshares.

**Comment by svbergerem** [comment]
@SuperTux88 Thanks, fixed. :)

https://github.com/diaspora/diaspora/pull/7520/commits/18256f3709c0376e359eba234396b00a8d097bea#diff-bfcc7b885f15994d21ecaef175e7e676

**Review by SuperTux88 — APPROVED** [review]
Works 👍

**Comment by SuperTux88** [comment]
Merged, thanks 👍

**Pull request merged**
