### PR TITLE
'Log out' becomes 'Log Out'

### PR DESCRIPTION
**Pull request by ghost**
More menu-based capitalisation consistency where "Log out" becomes "Log Out".

### CODE REVIEW

**Comment by goobertron** [comment]
Hmm, well it's good to make it more consistent, but personally I'd rather move away from Capitals At The Start Of Each Word. But that's a future discussion. Thanks for the PR.

**Comment by jhass** [comment]
Shouldn't we make this a one go to consistency everywhere?

I'd also tend to not titlecase at all.

**Comment by RichKavanagh** [comment]
I was basing this PR on #5506

I'm not fussed which way round the casing is, or isn't, so long as it is consistent throughout Diaspora because right now it's all over the place and looks terrible.

**Comment by goobertron** [comment]
I did start, a few months ago, making the capitalisation consistent in the en locale, but I got really bogged down in it and never finished the work. If there is agreement to use sentence case (i.e. normal English capitalisation rules) rather than Caps For Every Word, I'll try to complete this work.

**Comment by RichKavanagh** [comment]
Cheers @goobertron I've fired it over to [this Loomio thread](https://www.loomio.org/d/kY0wClao/capitalisation) for wider discussion.

@jhass will you be merging these recent capitalisation PRs while we wait for a final decision to be reached?

**Comment by jhass** [comment]
I'd rather like a policy and then make it consistent in one go kind of approach, but then I'm not the only one with commit rights ;)

**Comment by RichKavanagh** [comment]
Ha! Cool tag, thanks :+1:

**Comment by jaywink** [comment]
Well, according to the recently finished Loomio vote, sentence capitalization seems to rule the land. So closing this. #5579 can be taken over by anyone wanting to fix these things maybe?

Tnx anyway @RichKavanagh :)

**Comment by goobertron** [comment]
I'm on it.

**Pull request closed without merging**
