### PR TITLE
switch back to jquery-colorbox

### PR DESCRIPTION
**Pull request by pravi**
they provide the same assets and name change was not intentional

### CODE REVIEW

**Comment by Zauberstuhl** [comment]
related to diaspora/jsxc#126

**Comment by pravi** [comment]
@Zauberstuhl we need to change application.scss as well. Where does it expect to find colorbox.scss? from diaspora_jsxc, I assume.

**Comment by Zauberstuhl** [comment]
@pravi you mean this https://github.com/diaspora/diaspora/blob/develop/app/assets/stylesheets/_application.scss#L75 ?

**Comment by pravi** [comment]
@Zauberstuhl yes. I can see rails-assets-jquery-colorbox does not have a colorbox.scss in app/assets/stylesheets but rails-assets-colorbox has

**Comment by pravi** [comment]
see http://anonscm.debian.org/cgit/pkg-ruby-extras/ruby-rails-assets-colorbox.git/tree/app/assets/stylesheets

and 

http://anonscm.debian.org/cgit/pkg-ruby-extras/ruby-rails-assets-jquery-colorbox.git/tree/app/assets/stylesheets

**Comment by pravi** [comment]
rails-assets-jquery-colorbox has colorbox.scss in jquery-colorbox/example1, jquery-colorbox/example2 ...

**Comment by Zauberstuhl** [comment]
that is totally weird..

both packages are using the same repository -> https://github.com/jackmoore/colorbox (check bower.io)

and latest versions:
[rails-assets-colorbox/version](http://anonscm.debian.org/cgit/pkg-ruby-extras/ruby-rails-assets-colorbox.git/tree/lib/rails-assets-colorbox/version.rb)
[rails-assets-jquery-colorbox/version](http://anonscm.debian.org/cgit/pkg-ruby-extras/ruby-rails-assets-jquery-colorbox.git/tree/lib/rails-assets-jquery-colorbox/version.rb)

**Comment by Zauberstuhl** [comment]
@pravi ignore the scss file and remove it from _application.scss that is a problem with bower-packaging. seams like they use the file only in there examples (like you already mentioned)

I'll test it later. cheers

**Comment by Zauberstuhl** [comment]
we have to merge this into develop related to #6488

**Comment by jaywink** [comment]
Great, merging this in then. The failing tests are not related to this. Thanks!

**Pull request merged**
