### PR TITLE
Updated capitalisation in conversation.rb

### PR DESCRIPTION
**Pull request by ghost**
Continuing the correct capitalisation of diaspora\* I have changed 'no subject' to become 'No subject'

### CODE REVIEW

**Comment by jhass** [comment]
Oh wow, good catch. Could you extract this to a translation key?

**Comment by RichKavanagh** [comment]
It needs it for sure, but I'm afraid that is way beyond my non-existent RoR skillset :(

**Comment by jhass** [comment]
Hey, it's how  I started! Just take a peek at config/locals/en.yml and call `I18n.t('my.super.awesome.key')`.

**Comment by denschub** [comment]
@RichKavanagh Ping!

**Comment by RichKavanagh** [comment]
@denschub Pong!

**Comment by denschub** [comment]
You are not done with this PR and I get very sad when pull requests are orphaned... Do you mind extracting your translation into actual langauge files as Jonne suggested?

**Comment by RichKavanagh** [comment]
Don't be sad mate, it's Thursday!

This hasn't changed I'm afraid:

> It needs it for sure, but I'm afraid that is way beyond my non-existent RoR skillset :(

So if you're worried about this being 'orphaned', just kill it mate :+1:

**Comment by denschub** [comment]
Nah. That's an excuse I won't accept here. ;)

As Jonne said, just add the key to `config/locales/diaspora/en.yml` (the syntax should be familiar to you) and replace the string with `I18n.t('my.super.awesome.key')`, where `my.super.awesome.key` is the chain of labels in your `yml` file. You can do it!

**Comment by RichKavanagh** [comment]
For some reason I was unable to edit this #5999 PR. So instead I created two new ones as detailed above and I'll close this one :+1:

**Pull request closed without merging**
