### PR TITLE
Display reshared poll

### PR DESCRIPTION
**Pull request by svbergerem**
Supersedes #4928 and #5565.

### CODE REVIEW

**Comment by goobertron** [comment]
Nice work! How about, for the text, "You can participate in this poll on the <%= original_post_link %>." Your text is fine, but this version seems, I think, a little less formal and more inviting.

**Comment by svbergerem** [comment]
@goobertron Thank you for your suggestion. I changed the text.

**Comment by goobertron** [comment]
Great, thanks!

**Comment by jhass** [comment]
Thank you!

**Pull request merged**
