### PR TITLE
Add popover/tooltip about email visibility to registration/settings page

### LINKED ISSUE #5315: Indicates in the setting that the email is not visibile to the other users
I have a user who asked me about that, we can make that more clear. I'm probably going to open a PR soon, just open this issue as a reminder.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/5182270-indicates-in-the-setting-that-the-email-is-not-visibile-to-the-other-users?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by svbergerem**
Fixes #5315, supersedes #5692.
registration
settings

### CODE REVIEW

**Comment by svbergerem** [comment]
One randomly failing spec. Should be ready to merge.

**Comment by goobertron** [comment]
Thanks for this. Just a thought: would it be a good idea (and easy to implement) to show this tooltip when someone focuses the email field? That way everyone would see the advice before entering and email address. I haven't tested  it yet, but I assume it only displays when hovering the envelope icon.

**Comment by svbergerem** [comment]
@goobertron 
> I haven't tested it yet, but I assume it only displays when hovering the envelope icon.

No, it doesn't. :) In the settings view the tooltip is displayed when hovering the lock icon but on the registration page the popover is visible while the email field is focused and I added autofocus for the email field.

**Comment by goobertron** [comment]
Brilliant! You are a star!

**Comment by denschub** [comment]
Merged as 3ae370780c34e3cf77138273eeb2d6dbceea3cf8, Thank you!

**Pull request closed without merging**
