### PR TITLE
API

### PR DESCRIPTION
**Pull request by jhass**
"Rebased" version of #7462 to clear out any !fixup's

### CODE REVIEW

**Comment by jhass** [comment]
So this has an extra commit to undo some merge conflict hassle vs the original PR has some `!fixup`s not being rebased out. Pick whatever you find cleaner :)

**Comment by jhass** [comment]
:sparkling_heart:

**Comment by denschub** [comment]
# 🎉 

Thanks to everyone who worked on this project, past and present. This is *huge*. :)

**Comment by Flaburgan** [comment]
Thanks to everybody involved here, and special thanks to @KentShikama, @frankrousseau  and @HankG who did an awesome job!

**Comment by HankG** [comment]
Very exciting news! Thanks to the whole team who helped bring this to fruition!

**Comment by frankrousseau** [comment]
It almost sounds like a miracle! I hope it will bring a lot of new capabilities to the Diaspora project.
Thank you for the review, the rebase and the merge!

**Comment by DeadSuperHero** [comment]
Wow, this is incredible! Congrats on finally getting this merged.

**Comment by wiegelmann** [comment]
Dreams come true. Many thanks!

**Comment by stragu** [comment]
So does that mean that the people who worked on it can claim this? https://www.bountysource.com/issues/295-api-needed

**Comment by Flaburgan** [comment]
Yes!

**Pull request merged**
