### PR TITLE
Original white background - Color Theme

### PR DESCRIPTION
**Pull request by jpope777**
This adds a color theme which has the all white background similar to the previous D\* css.

### CODE REVIEW

**Comment by svbergerem** [comment]
I can haz screenshots? :)

**Comment by jpope777** [comment]
Oof. I suppose I could have done that. ;)

snapshot110

Also posted [here](https://pod.jpope.org/posts/fde729e03cd6013304ab0f1e2657a9dd).

**Comment by Zauberstuhl** [comment]
:+1:

**Comment by svbergerem** [comment]
I think you can have the same style changes with less code changes:
```diff
diff --git a/app/assets/stylesheets/color_themes/_color_theme_override_origwhite.scss b/app/assets/stylesheets/color_themes/_color_theme_override_origwhite.scss
index 7bd0073..508679a 100644
--- a/app/assets/stylesheets/color_themes/_color_theme_override_origwhite.scss
+++ b/app/assets/stylesheets/color_themes/_color_theme_override_origwhite.scss
@@ -2,22 +2,10 @@
 body {
   #left-navbar .hoverable { border-bottom: none; }
 
-  #left-navbar-fixed-sub-background { background: $sidebars-background; }
-  #left-navbar-fixed-background {
-    background: $sidebars-background;
+  #left-navbar-fixed-background, #left-navbar {
     border-right: 1px solid $sidebars-background;
   }
-  #left-navbar {
-    background: $sidebars-background;
-    border-right: 1px solid $sidebars-background;
-  }
-  #right-sidebar-fixed-sub-background { background: $sidebars-background; }
-  #right-sidebar-fixed-background {
-    background: $sidebars-background;
-    border-left: 1px solid $sidebars-background;
-  }
-  .rightbar {
-    background: $sidebars-background;
+  #right-sidebar-fixed-background, .rightbar {
     border-left: 1px solid $sidebars-background;
   }
 }
diff --git a/app/assets/stylesheets/color_themes/original_white/_style.scss b/app/assets/stylesheets/color_themes/original_white/_style.scss
index 1885c56..cfbf1c7 100644
--- a/app/assets/stylesheets/color_themes/original_white/_style.scss
+++ b/app/assets/stylesheets/color_themes/original_white/_style.scss
@@ -8,5 +8,6 @@ $main-color-dark: darken($main-color, 15%);
 /* Variables */
 $header-background-color: $main-color-dark;
 $sidebars-background: $background;
+$sidebars-sub-background: $background;
 
 @import "color_themes/color_theme_override_origwhite"
diff --git a/app/assets/stylesheets/colors.scss b/app/assets/stylesheets/colors.scss
index b36b09f..905de1c 100644
--- a/app/assets/stylesheets/colors.scss
+++ b/app/assets/stylesheets/colors.scss
@@ -25,8 +25,8 @@ $red: #A80000;
 $blue: #3F8FBA;
 $dark-blue: darken(#0984C8,10%);
 
-$sidebars-background: #f0f0f0;
-$sidebars-sub-background: darken($sidebars-background, 12%);
+$sidebars-background: #f0f0f0 !default;
+$sidebars-sub-background: darken($sidebars-background, 12%) !default;
 $left-navbar-drawer-background: darken($sidebars-background, 6%);
 
 /* colors : http://www.colourlovers.com/palette/2134203/Awezome_in_argyle */
```

**Comment by jpope777** [comment]
Yeah, I've realized this as I'm playing with another theme. I'll condense it down more now that I have a better understanding of scss. ;)

**Comment by Flaburgan** [comment]
I'm wondering, because the template of the design is still going to change, who will have to fix the themes, in general? The one who changes the markup, or the one who created the theme?

**Comment by svbergerem** [comment]
Superseded by #6631. Thank you.

**Pull request closed without merging**
