### PR TITLE
Include PostsHelper in NotifierHelper

### PR DESCRIPTION
**Pull request by skyschub**
@SuperTux88 ideally, this needs tests. However, this seems to only fail in the context of Sidekiq runs, see https://github.com/diaspora/diaspora/issues/7852#issuecomment-418221263. Any idea off the top of your head on how to either test this or how to make Sidekiq behave the same as the fronted?

### CODE REVIEW

**Comment by denschub** [comment]
Are.. you sure? This

```diff
diff --git a/spec/mailers/notifier_spec.rb b/spec/mailers/notifier_spec.rb
index 002014b05..f78de731d 100644
--- a/spec/mailers/notifier_spec.rb
+++ b/spec/mailers/notifier_spec.rb
@@ -214,6 +214,13 @@ describe Notifier, type: :mailer do
       like = reshare.likes.create!(author: bob.person)
       Notifier.send_notification("liked", alice.id, like.author.id, like.id)
     end
+
+    it "can handle status_messages without text" do
+      photo = FactoryGirl.create(:photo, public: true)
+      status = FactoryGirl.create(:status_message, author: alice.person, text: nil, photos: [photo], public: true)
+      like = status.likes.create!(author: bob.person)
+      Notifier.send_notification("liked", alice.id, like.author.id, like.id)
+    end
   end

   describe ".reshared" do
```

is green, without including the helper.

**Comment by SuperTux88** [comment]
Interesting ... I searched a while to find what I did different yesterday than you did ... but it looks like the mail body is only rendered, when you read it. So this works:

```diff
diff --git a/spec/mailers/notifier_spec.rb b/spec/mailers/notifier_spec.rb
index 002014b05..47841e014 100644
--- a/spec/mailers/notifier_spec.rb
+++ b/spec/mailers/notifier_spec.rb
@@ -214,6 +214,14 @@ describe Notifier, type: :mailer do
       like = reshare.likes.create!(author: bob.person)
       Notifier.send_notification("liked", alice.id, like.author.id, like.id)
     end
+
+    it "can handle status_messages without text" do
+      photo = FactoryGirl.create(:photo, public: true)
+      status = FactoryGirl.create(:status_message, author: alice.person, text: nil, photos: [photo], public: true)
+      like = status.likes.create!(author: bob.person)
+      mail = Notifier.send_notification("liked", alice.id, like.author.id, like.id)
+      expect(mail.body.encoded).to include(I18n.t("posts.show.photos_by", count: 1, author: alice.name))
+    end
   end

   describe ".reshared" do
```

**Comment by denschub** [comment]
Ah! You are right! Updated the PR.

**Review by SuperTux88 — APPROVED** [review]

**Comment by SuperTux88** [comment]
Merged as 65a2b8da12052495df2fe3c5815b1aed13206ab8

Thank you :cookie:

**Pull request closed without merging**
