### PR TITLE
Include Handlebars templates to main.js

### PR DESCRIPTION
**Pull request by cmrd-senya**
This is needed to properly initialize Handlebars partials without a document ready handler.

ref #7739

### CODE REVIEW

**Comment by SuperTux88** [comment]
I don't know how to reproduce this in develop mode, and even in production it sometimes takes many tries until it happens, so it's difficult for me to test this.

But I don't know if this is the "correct" way of fixing this. It somehow makes sense to me, that registering it earlier probably solves the problem, I have no idea if this has other side-effect (especially because the comment probably had a reason and I don't know if this still is needed). Maybe @denschub can have a look at it and say if this is a good solution or if it should be done in a different way.

**Comment by cmrd-senya** [comment]
I reproduced it in development by creating a profile with a reshare and then I opened it in a background tab (with a middle mouse button click).

> especially because the comment probably had a reason and I don't know if this still is needed

This code was originally introduced in 2012, here is the first revision: https://github.com/diaspora/diaspora/blob/5d051fcc5226c855d726c64647d5f04fbc40cf08/public/javascripts/app/helpers/handlebars-partials.js

At this point `handlebars_assets` gem wasn't used as the assets pipeline too. So the comment had a reason back then when there probably was some initializing code at the javascript app which had to be called first.

Now we're using `handlebars_assets` gem: https://github.com/leshill/handlebars_assets

The documentation for the gem explicitly [says](https://github.com/leshill/handlebars_assets#templates-directory) that you should require the templates at the javascript application main file (e.g. `app/assets/javascripts/application.js`). `handlebars_assets` will take care of loading the templates now during assets compilation, so no need to set document ready handlers anymore.

What I have done here is:
1) Fixed requiring templates according with the documentation of  `handlebars_assets`
2) Removed some legacy code

So the fix feels quite "correct" to me.

**Comment by cmrd-senya** [comment]
It is deterministic that we register the partial when the template is already loaded because the `handlebars-partials.js` is required after the templates are required in the `app.js` so I don't think there are any side effects.

**Comment by SuperTux88** [comment]
Thanks for the explanation, I think I understand now how it worked before and what you did here. :+1: 

But now as you include the templates to the `main.js` the templates are included twice, because they are also included in the application template here:

https://github.com/diaspora/diaspora/blob/8e88f4b18370a3877631277569d1d0ef5bbc6612/app/views/layouts/application.html.haml#L11

And they don't need to be precompiled separately anymore when they are included in the `main.js`, so this can be removed too:

https://github.com/diaspora/diaspora/blob/398235ee6f0ed23b4e95ffa7228025d87237600c/app/assets/config/manifest.js#L9

And maybe remove the `templates.js` file completely and include it with `require_tree` as described in the `handlebars_assets`.

**Comment by cmrd-senya** [comment]
Updated

**Review by SuperTux88 — APPROVED** [review]
Looks good to me and seems to fix the bug on my develop pod.

**Comment by SuperTux88** [comment]
Merged as f632f8a1f8fef3e7c9303c2ef373d72b929994aa

Thanks for debugging and fixing that :cookie:

**Pull request closed without merging**
