### PR TITLE
Issue #6164: fix cyrrilic 'б' in tags input. Move comma validation fr…

### PR DESCRIPTION
**Pull request by AntonTkachov**
…om keydown to keypress event

### CODE REVIEW

**Comment by AntonTkachov** [comment]
Fixes #6164

**Comment by svbergerem** [comment]
Our autoSuggest code is based on an outdated version of autoSuggest and [it looks like the project is no longer maintained](https://github.com/wuyuntao/jquery-autosuggest). I think instead of adding yet another patch to some piece of code that is unmaintained and not covered by any tests, we should look for alternatives and use those. I started to do something similar for autocomplete in #6293 so I think a typeahead.js based alternative would be great.

**Comment by AntonTkachov** [comment]
@svbergerem So, do you think we should just suspend this task and close pull request for now or should I try to make this pull request properly path Travis validation?

**Comment by svbergerem** [comment]
> do you think we should just suspend this task and close pull request for now

Yes, I think so. Since we don't have any jasmine tests here we can neither make sure that everything else works like it did before (without doing manual tests) nor make sure that the fixed behaviour won't break with further changes. Since we are planning to replace that unmaintained code I don't think it is worth the effort if we would write our own tests.

Nevertheless, thank you for your work.

**Pull request closed without merging**
