### PR TITLE
Add initial posts and author routes for API

### PR DESCRIPTION
**Pull request by KentShikama**
These routes should comply with http://jsonapi.org/format/.

The following routes have been added:

api_v0_post_relationships_author
- Scope: read  
- /api/v0/posts/:post_id/relationships/author(.:format)  
- api/v0/posts#show_relationship {:relationship=>"author"}
- This gets the author relationship of the post.

api_v0_post_author
- Scope: read  
- /api/v0/posts/:post_id/author(.:format)  
- api/v0/people#get_related_resource {:relationship=>"author", :source=>"api/v0/posts"}
- This gets the author of the post unless the author's account has closed

api_v0_posts
- Scope: read/write 
- /api/v0/posts(.:format)  
- api/v0/posts#create
- This creates a posts and sends it to the aspects specified in data/attributes/aspect_ids

api_v0_post          
- Scope: read  
- /api/v0/posts/:id(.:format)  
- api/v0/posts#show
- This gets post by its id or guid if it is visible from the current user.

api_v0_person_relationships_posts                     
- Scope: read  
- /api/v0/people/:person_id/relationships/posts(.:format) 
- api/v0/people#show_relationship {:relationship=>"posts"}
- This gets the relationship ids of the post that are visible from the current user.

api_v0_person_posts
- Scope: read  
- /api/v0/people/:person_id/posts(.:format)  
- api/v0/posts#get_related_resources {:relationship=>"posts", :source=>"api/v0/people"}
- This gets the contents of the posts that are visible from the current user.

api_v0_person
- Scope: openid  
- /api/v0/people/:id(.:format)  
- api/v0/people#show
- This gets the person from their guid or diaspora handle.

See the tests for more details.

### CODE REVIEW

**Comment by theworldbright** [comment]
Also this is my first attempt at monkey-patching – I would be happy to learn any cleaner methods of overriding the gem.

**Comment by jhass** [comment]
Why are they needed at all again? Will take a deeper look at this later.

**Comment by theworldbright** [comment]
Also what is the issue here? I'm using ruby-2.2.1@diaspora locally and I'm having no issues.

https://travis-ci.org/diaspora/diaspora/jobs/101870706#L449

**Comment by jhass** [comment]
Well, the build is for 2.1 as we still support that, you still need the old hash literal syntax there for 2.1.

**Comment by theworldbright** [comment]
Oh lol…I misread 2.2.1 as 2.1.2 (or 2.1 something).

**Comment by theworldbright** [comment]
See https://www.loomio.org/d/OUfjC7DI/request-for-comments-api-specification-draft?utm_campaign=missed_yesterday&utm_medium=email&utm_source=user_mailer

**Pull request closed without merging**
