### PR TITLE
Update CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by jart**

### CODE REVIEW

**Comment by denschub** [comment]
I'm sorry?

**Comment by svbergerem** [comment]
“follow the law” isn't really helpful for a project with contributors from different countries. I'd prefer to keep our current code of conduct.

**Comment by jart** [comment]
Are you a lawyer @svbergerem?

**Comment by cmrd-senya** [comment]
Since diaspora is a community governed project, changes to the code of conduct should be approved by voting at [Loomio group](https://www.loomio.org/g/EseV9p4X/diaspora-community) first. You can rise a discussion and voting to verify if your proposal is acceptable for the community.

**Pull request closed without merging**
