### PR TITLE
WIP - Refactor users#update action

### PR DESCRIPTION
**Pull request by oliverbarnes**
This is a partial WIP of the refactor asked for on #3664. After a while sitting on it, it's clear I won't be able to finish it in a timely fashion, as I'm too caught up with my day job. Hopefully this can be a good starting point for somebody else to adopt and continue?

The approach I've taken is to extract logic branches into small discreet controllers. Two so far: User::EmailPreferencesController and User::PasswordController. These also map to separate forms on the user edit page. 

Did the same to their specs. Haven't touched the cucumber features yet.

### CODE REVIEW

**Comment by denschub** [comment]
Closing this PR. This now will result in a massive list of merge conflicts. It has been orphaned for more than a year and old pull requests look kinda sad. Feel free to reopen this if there is a need to.

**Comment by cmrd-senya** [comment]
Does it worth adopting now?

**Comment by denschub** [comment]
Not really. While cleaning up is a nice idea, we should probably build Services now.

**Comment by cmrd-senya** [comment]
Then #3664 should be updated probably.

**Comment by denschub** [comment]
You are very right! Done.

**Pull request closed without merging**
