### PR TITLE
Add 'Be excellent to each other!' to the sidebar

### PR DESCRIPTION
**Pull request by skyschub**
Supersedes #6908 after some discussions via IRC.

screen shot 2016-07-11 at 23 10 48

### CODE REVIEW

**Comment by Flaburgan** [comment]
Just tested this locally, the code is fine and everything works well so it's a :+1: 
Although you can increase a little bit the font size if you want to, it's hardly readable on a 1920px width screen.

**Comment by svbergerem** [comment]
Here are two versions. The left one is a screenshot with the original code, for the right one I added `font-size: $font-size-base;`. I'm unable to decide which one I'd prefer.

excellent

**Comment by tchncs** [comment]
What about centered?
2016-07-13-100105_1920x1200_scrot

**Comment by svbergerem** [comment]
And with the bigger font:
excellent centered

Since this would be the only centered text in the sidebar I fear that this will make too much “noise”.

**Comment by tchncs** [comment]
Hmm but maybe it would be good to make something like this as a podmin-controllable motd.
In an own box: 


2016-07-13-110120_1920x1200_scrot


The current way is like a branding, maybe not every podmin wanna have this there and maybe not every one knows how to change it to own preference - just my personal thinking about.
To have this as a default motd which can be changed by the podmins, might be a more elegant way and brings a neat new feature .... and it's maybe more beautiful and more solid looking. :3

**Comment by svbergerem** [comment]
@tchncs I think that this is out of scope for this PR and it's even more noise for the left sidebar which is really clean right now. There is also the “Welcome new users” section that you might call branding that not all podmins would like to have on their pods.

I think we should just make the font a little bit bigger and then this should be ready to merge.

**Comment by svbergerem** [comment]
Thank you! :)

**Comment by jpope777** [comment]
> "some discussions via IRC"
Anyone have a log of these discussions?

**Comment by denschub** [comment]
IRC discussions were about the actual design of this element, not the contents or the usefulness. Discussions about adding a message as a start and following up with more community guidelines was/is done [on Loomio](https://www.loomio.org/d/F5zxTwiX/diaspora-statement) as usual.

**Pull request merged**
