### PR TITLE
Move PostHelper#post_page_title to PostPresenter#title.

### LINKED ISSUE #6997: For posts with no message, title set at first on the page is different from title later loaded from the json
It results in a flash in the title bar when loading the page. Which title should be set?

Maybe the post_page_title method from the posts helper should be be the only way to define a title for a post (and thus should be in the post presenter class).

### PR DESCRIPTION
**Pull request by dhovart**
Fixes #6997 
Added a few more tests as well.

### CODE REVIEW

**Comment by SuperTux88** [comment]
@dhovart did you delete this branch by accident?

**Comment by dhovart** [comment]
Well, I submitted this, there was no reaction whatsoever and later on looking at my changes I got quite ashamed of this pull request. I just wanted to get rid of it to submit a cleaner one later on. This branch is not to be merged yet. `PostPresenter.new(post).title` is kind of awful, I don't know why I wrote that ; this should not be an instance method if used this way (there's several of them).
I’m going to correct this and resubmit a pull request this week.

This is one of my first rails project and I'm quite insecure, sorry for this.

**Comment by denschub** [comment]
> there was no reaction whatsoever and later on looking at my changes I got quite ashamed of this pull request

Oh, don't worry. The lack of fast reaction is usually not the fault of the person submitting the PR, we are just really slow with reviewing them sometimes. :)

**Comment by SuperTux88** [comment]
Also, you can update a PR, no need to create a new one :)

**Pull request closed without merging**
