### PR TITLE
Fix Bootstrap3 regression: reshares in SPV

### PR DESCRIPTION
**Pull request by svbergerem**
### root post

**before:** 
spv_reshare_root_before

**after:**
spv_reshare_root_after
### reshare

**before:**
spv_reshare_reshare_before

**after:**
spv_reshare_reshare_after

### CODE REVIEW

**Comment by Flaburgan** [comment]
Oh, was working on this one :) The border is still not fine imo but let's merge this and I'll polish it.

**Comment by svbergerem** [comment]
@Flaburgan what is wrong with which border?

**Comment by Flaburgan** [comment]
@svbergerem the horizontal borders: they are not aligned with the avatars in the left, and are touching the vertical border at the right. Currently master is looking like that:

capture du 2015-06-07 13 22 20

**Comment by svbergerem** [comment]
Well, I'm ok with the current borders. If you have a different opinion about that then just open a new PR afterwards and we can discuss over there.

**Comment by Flaburgan** [comment]
Fair enough :)

**Comment by jhass** [comment]
Thanks!

**Pull request merged**
