### PR TITLE
Mobile: manage followed tags

### LINKED ISSUE #5367: Add a way to follow a tag on the mobile version
When searching for a tag on the mobile version of the app, there doesn't seem to be a way to follow that tag on the result page.

Also there doesn't seem to be a way to view or manage subscribed tags.

<bountysource-plugin>
---
There is a **[$115 open bounty](https://www.bountysource.com/issues/5445631-add-a-way-to-follow-a-tag-on-the-mobile-version?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by svbergerem**
Fixes #5367.
manage followed tags

### CODE REVIEW

**Comment by Flaburgan** [comment]
Looks nice, thanks!

**Comment by goobertron** [comment]
Yes, definitely! Thanks.

**Comment by denschub** [comment]
Merged as 40bb44eb96e8dcef75ca003040260c1c06d61254, thank you very much! :cookie:

**Comment by davidbaumann** [comment]
Thanks for this. But how can I follow a tag?
With the desktop version, I can click in the tag, in mobile, I cant. https://despora.de/tags/bmw

**Comment by Flaburgan** [comment]
Check the milestone: this feature is not available in the current release, it is coming with the next release.

**Comment by davidbaumann** [comment]
I understand. But how to follow a tag? Regarding the screenshots, I can only see how to manage existing tags.

**Comment by Flaburgan** [comment]
This is done on a different pull request: https://github.com/diaspora/diaspora/pull/5941

**Comment by davidbaumann** [comment]
Thanks!

**Pull request closed without merging**
