### PR TITLE
Speed up public stream and remove obsolete indexes

### PR DESCRIPTION
**Pull request by CSammy**
Speeds up the public stream by a factor of 1000 on a production PostgreSQL database, it's lightning fast now. MySQL shows improvement as well.

### CODE REVIEW

**Comment by goobertron** [comment]
Whaouh – I can't test this, but this could be BIG. Sharing some love for this.

**Review by SuperTux88 — APPROVED** [review]
Looks good to me, also improves MySQL performance by a factor of 10 on an old export of my prod DB on my dev-pod. Thanks for the analysis :cookie: Migration took around 15s on my dev-pod with MySQL, so should be OK for a minor release.

**Comment by SuperTux88** [comment]
Merged as a21cde4c0066f9a5338ba8fb906d979642a05333

Thanks again @CSammy :cookie: 

@goobertron you can now test the speed of it on the HQ-pod :)

**Comment by Flaburgan** [comment]
\o/ Now, to the user stream! :stuck_out_tongue:

**Comment by koehn** [comment]
I manually made this change to a copy of my production database and didn't see any real performance gain. Is there something I'm missing?

```
diaspora_production=> \d posts
                                              Table "public.posts"
        Column         |            Type             | Collation | Nullable |              Default              
-----------------------+-----------------------------+-----------+----------+-----------------------------------
 id                    | integer                     |           | not null | nextval('posts_id_seq'::regclass)
 author_id             | integer                     |           | not null | 
 public                | boolean                     |           | not null | false
 guid                  | character varying(255)      |           | not null | 
 type                  | character varying(40)       |           | not null | 
 text                  | text                        |           |          | 
 created_at            | timestamp without time zone |           | not null | 
 updated_at            | timestamp without time zone |           | not null | 
 provider_display_name | character varying(255)      |           |          | 
 root_guid             | character varying(255)      |           |          | 
 likes_count           | integer                     |           |          | 0
 comments_count        | integer                     |           |          | 0
 o_embed_cache_id      | integer                     |           |          | 
 reshares_count        | integer                     |           |          | 0
 interacted_at         | timestamp without time zone |           |          | 
 tweet_id              | character varying(255)      |           |          | 
 open_graph_cache_id   | integer                     |           |          | 
 tumblr_ids            | text                        |           |          | 
Indexes:
    "posts_pkey" PRIMARY KEY, btree (id)
    "index_posts_on_author_id_and_root_guid" UNIQUE, btree (author_id, root_guid)
    "index_posts_on_guid" UNIQUE, btree (guid)
    "index_posts_on_created_at" btree (created_at)
    "index_posts_on_id_and_type" btree (id, type)
    "index_posts_on_person_id" btree (author_id)
    "index_posts_on_root_guid" btree (root_guid)
Foreign-key constraints:
    "posts_author_id_fk" FOREIGN KEY (author_id) REFERENCES people(id) ON DELETE CASCADE
```

**Comment by koehn** [comment]
Here's the `explain analyze` on the stream query (TL;DR 7 seconds):
```
                                                                                                                      QUERY PLAN                                                                                                                      
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=299373.11..299373.52 rows=15 width=20) (actual time=6895.803..6895.813 rows=15 loops=1)
   ->  Merge Append  (cost=299373.11..299373.93 rows=30 width=20) (actual time=6895.802..6895.808 rows=15 loops=1)
         Sort Key: posts.created_at DESC
         ->  Limit  (cost=297907.69..297907.84 rows=15 width=20) (actual time=6891.223..6891.228 rows=15 loops=1)
               ->  Unique  (cost=297907.69..302195.26 rows=428757 width=20) (actual time=6891.222..6891.227 rows=15 loops=1)
                     ->  Sort  (cost=297907.69..298979.59 rows=428757 width=20) (actual time=6891.220..6891.222 rows=15 loops=1)
                           Sort Key: posts.created_at DESC, posts.id, posts.updated_at
                           Sort Method: external merge  Disk: 7016kB
                           ->  Hash Right Join  (cost=242830.60..249002.40 rows=428757 width=20) (actual time=4288.171..6699.149 rows=210805 loops=1)
                                 Hash Cond: (share_visibilities.shareable_id = posts.id)
                                 Filter: (((share_visibilities.user_id = 1) AND ((share_visibilities.shareable_type)::text = 'Post'::text) AND (NOT share_visibilities.hidden)) OR posts.public)
                                 Rows Removed by Filter: 15053
                                 ->  Seq Scan on share_visibilities  (cost=0.00..2274.80 rows=87575 width=14) (actual time=0.018..19.113 rows=87683 loops=1)
                                       Filter: ((shareable_type)::text = 'Post'::text)
                                       Rows Removed by Filter: 32861
                                 ->  Hash  (cost=234840.87..234840.87 rows=435178 width=21) (actual time=4273.430..4273.430 rows=212510 loops=1)
                                       Buckets: 65536  Batches: 8  Memory Usage: 2001kB
                                       ->  Hash Join  (cost=1722.22..234840.87 rows=435178 width=21) (actual time=2.940..3575.832 rows=212510 loops=1)
                                             Hash Cond: (posts.author_id = people.id)
                                             ->  Seq Scan on posts  (cost=0.00..223877.44 rows=3515896 width=25) (actual time=0.079..3283.006 rows=3515896 loops=1)
                                                   Filter: (((type)::text = ANY ('{StatusMessage,Reshare}'::text[])) AND (created_at < '2018-12-29 20:20:37'::timestamp without time zone))
                                             ->  Hash  (cost=1717.17..1717.17 rows=404 width=4) (actual time=2.578..2.579 rows=385 loops=1)
                                                   Buckets: 1024  Batches: 1  Memory Usage: 22kB
                                                   ->  Unique  (cost=1711.11..1713.13 rows=404 width=4) (actual time=2.486..2.532 rows=385 loops=1)
                                                         ->  Sort  (cost=1711.11..1712.12 rows=404 width=4) (actual time=2.486..2.495 rows=401 loops=1)
                                                               Sort Key: people.id
                                                               Sort Method: quicksort  Memory: 43kB
                                                               ->  Nested Loop  (cost=94.20..1693.62 rows=404 width=4) (actual time=0.260..2.375 rows=401 loops=1)
                                                                     ->  Hash Join  (cost=93.91..253.14 rows=404 width=4) (actual time=0.249..1.204 rows=401 loops=1)
                                                                           Hash Cond: (contacts.id = aspect_memberships.contact_id)
                                                                           ->  Seq Scan on contacts  (cost=0.00..105.17 rows=5717 width=8) (actual time=0.011..0.458 rows=5717 loops=1)
                                                                           ->  Hash  (cost=88.86..88.86 rows=404 width=4) (actual time=0.228..0.228 rows=401 loops=1)
                                                                                 Buckets: 1024  Batches: 1  Memory Usage: 23kB
                                                                                 ->  Bitmap Heap Scan on aspect_memberships  (cost=42.26..88.86 rows=404 width=4) (actual time=0.058..0.185 rows=401 loops=1)
                                                                                       Recheck Cond: (aspect_id = ANY ('{1,2,3,4,5,14,15,16,17,59,101}'::integer[]))
                                                                                       Heap Blocks: exact=37
                                                                                       ->  Bitmap Index Scan on index_aspect_memberships_on_aspect_id_and_contact_id  (cost=0.00..42.16 rows=404 width=0) (actual time=0.047..0.047 rows=401 loops=1)
                                                                                             Index Cond: (aspect_id = ANY ('{1,2,3,4,5,14,15,16,17,59,101}'::integer[]))
                                                                     ->  Index Only Scan using people_pkey on people  (cost=0.29..3.57 rows=1 width=4) (actual time=0.003..0.003 rows=1 loops=401)
                                                                           Index Cond: (id = contacts.person_id)
                                                                           Heap Fetches: 401
         ->  Limit  (cost=1465.40..1465.55 rows=15 width=20) (actual time=4.578..4.578 rows=1 loops=1)
               ->  Unique  (cost=1465.40..1470.65 rows=525 width=20) (actual time=4.576..4.576 rows=1 loops=1)
                     ->  Sort  (cost=1465.40..1466.72 rows=525 width=20) (actual time=4.575..4.575 rows=1 loops=1)
                           Sort Key: posts_1.created_at DESC, posts_1.id, posts_1.updated_at
                           Sort Method: quicksort  Memory: 375kB
                           ->  Index Scan using index_posts_on_person_id on posts posts_1  (cost=0.43..1441.68 rows=525 width=20) (actual time=0.036..3.486 rows=3570 loops=1)
                                 Index Cond: (author_id = 1)
                                 Filter: (((type)::text = ANY ('{StatusMessage,Reshare}'::text[])) AND (created_at < '2018-12-29 20:20:37'::timestamp without time zone))
 Planning time: 1.558 ms
 Execution time: 7030.680 ms
```

**Comment by goobertron** [comment]
> @goobertron you can now test the speed of it on the HQ-pod :)

I also haven't noticed a dramatic improvement on the HQ pod. From manual timing of how long the 'spinning wheel' is present, it's 7 seconds on the `/public` stream versus 9 seconds on the main `/stream`.

**Comment by koehn** [comment]
Ahh, I thought this was about the `/stream` query based on a conversation online. My bad; disregard my earlier comments.

**Comment by koehn** [comment]
Looking into the `explain` of the stream query, it's doing a full table scan on `posts` because `created_at` is a `timestamp without time zone`. Is there any reason we don't have a time zone on these columns?

**Review by Stivovo — COMMENTED** [review]
/db/migrate/20181227235201_clean_up_posts_indexes.rb

**Pull request closed without merging**
