### PR TITLE
7714 twitter char overflow bugfix

### PR DESCRIPTION
**Pull request by HankG**

### CODE REVIEW

**Comment by HankG** [comment]
Please don't bother reviewing until I "fix" my commit style to match project preferences...

**Review by skyschub — APPROVED** [review]

**Comment by denschub** [comment]
Merged as 211e5cd1bc2900a337cc8fdf21fbe07702625bcc. Thanks.

**Comment by HankG** [comment]
My pod is now running 0.7.5.0.  The overflowed Diaspora post is truncated but there is no link in it to the Diaspora post.  I've manually inspected the test and it is building truncated messages under the same conditions. Yet the URL is not showing up in Twitter.  

Please reopen this so I can investigate fixing this further. 

I also think I have no choice but to bite the bullet now and setup an integration test pod for myself so I can confirm this is working properly before submitting another pull request.  Sorry :(

**Comment by Flaburgan** [comment]
@HankG you can [register on my pod](https://diaspora-fr.org/i/d24d8737f3a9) and tell me to pull your commit once you have a fix you want to test in production.

**Comment by SuperTux88** [comment]
> The overflowed Diaspora post is truncated but there is no link in it to the Diaspora post.

I just tested it and it contains a link to the original post, so for me it's working.

> Please reopen this so I can investigate fixing this further.

I can't reopen the PR, but you can create a new PR if you have another fix you want to merge. Or if you have steps to reproduce you can also just create a new issue.

Or as fla said, you can use a pod running the development version (for example his, or [mine](nerdpol.ch), or setup you own) to test it before a release.

**Pull request closed without merging**
