### PR TITLE
Update devise-two-factor 3.0.3 -> 3.1.0

### PR DESCRIPTION
**Pull request by pravi**
Changes: https://github.com/tinfoil/devise-two-factor/compare/v3.0.3...v3.1.0

### CODE REVIEW

**Review by jhass — APPROVED** [review]

**Comment by tclaus** [comment]
I see here and other PRs of approved minor gem-appdates. Why are these stalled?

**Comment by Flaburgan** [comment]
We usually merge them before doing a minor release. But yeah this could be merged now if Dennis or SuperTux want to do it.

**Comment by denschub** [comment]
> We usually merge them before doing a minor release.

That's actually not quite true. We merge them when it makes sense.

Pravi opened [a lot of PRs](https://github.com/diaspora/diaspora/pulls/pravi), some of them are not done (PR need changes, PR is still marked as WIP, builds breaking, ...). We gain absolutely nothing from merging these PRs, and if I understand it correctly, the goal here is just to make diaspora\* upstream match whatever Debian has in their sources? That's fine, but since we have nothing to really gain here, we'd rather merge (and backport to the minor branch, which is the painful part) when the work is done.

**Comment by jhass** [comment]
Superseded by d7536dafe3f3d22541b9b670c48e177e0d1afd1d

**Pull request closed without merging**
