### PR TITLE
Bump ruby to 2.4

### PR DESCRIPTION
**Pull request by Flaburgan**
Just checking how travis will react to that.

[Ruby 2.4 changelog](https://www.ruby-lang.org/en/news/2016/12/25/ruby-2-4-0-released/)

### CODE REVIEW

**Comment by Flaburgan** [comment]
Well, looks like it's not available yet :p

**Comment by SuperTux88** [comment]
Yes, I've already tried it too, and it also failed locally, so I didn't try travis ;)

**Comment by SuperTux88** [comment]
I rebased this on `develop` after merging #7345, lets see what travis says now :) (local tests worked)

**Comment by SuperTux88** [comment]
Travis still doesn't like it 😿 (I only tested rspec and starting a pod and clicking a bit locally)

**Comment by Flaburgan** [comment]
Thanks @SuperTux88 for the webmock bump. Travis is happier now, the failing one looks like a randomly failing one.

**Review by SuperTux88 — APPROVED** [review]
Looks good to me now 👍

**Comment by SuperTux88** [comment]
Just for the record: [Support of Ruby 2.1 has ended](https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/)

**Comment by SuperTux88** [comment]
ruby 2.3.x doesn't compile with libssl-1.1 (which is default on debian stable ... another sign to upgrade to 2.4 when debian stable is too new for something :P )

Also: Sidekiq 5 only supports 2.2.2+, so if we want to upgrade sidekiq we need to switch too :)

**Review by cmrd-senya — APPROVED** [review]

**Review by skyschub — APPROVED** [review]
Oh well, let's do it!

**Comment by SuperTux88** [comment]
I rebased this and added a second commit to also install production gems on travis (to check compatibility with ruby versions).

**Review by skyschub — APPROVED** [review]
👍

**Comment by SuperTux88** [comment]
Let's do this 🎉

**Pull request merged**
