### PR TITLE
Fixed Issue #5626

### PR DESCRIPTION
**Pull request by sam09**

### CODE REVIEW

**Comment by svbergerem** [comment]
I see two ways to fix #5626:
1. add a margin to all paragraphs in the stream (the solution you chose)
2. reduce the margin-bottom of lists if there is no other list or paragraph below

This is how stream elements look like with your chosen solution (top: before, bottom: after)


The last paragraph in a post intentionally had no margin so I'd like to see what others think about the solution.

**Comment by jhass** [comment]
@sam09 ping, still interested in getting this in?

**Comment by sam09** [comment]
Yes.

**Comment by jhass** [comment]
I think what Steffen meant by outlining the alternative is that he would prefer it over your solution, and I have to agree ;)

**Comment by sam09** [comment]
Another thought is to have margin top set to a non zero value for lists. How about that?

**Comment by jhass** [comment]
Well, I think do would prefer to keep no margin between the top and the bottom of the post and only have margins between those elements if another precedes or follows.

**Pull request closed without merging**
