### PR TITLE
Added mobile buttons for streams

### PR DESCRIPTION
**Pull request by Muhannes**
Added two buttons in the mobile drawer. One to stream, and one to public stream.

### CODE REVIEW

**Comment by Flaburgan** [comment]
Don't worry about your branch, it was a hint for the next time. Since you opened this one from another branch, let's continue here and I'll close #7143 

So, I tested this branch on my Sony Z3C running Firefox OS (I don't have any Android device). To reduce the font-size is not the way to go, sorry, because the line-height is set just [the line under](https://github.com/diaspora/diaspora/blob/1fdc17d96cf5190a9e9ac069510c1985608a7a58/app/assets/stylesheets/mobile/header.scss#L152). So you can keep the font-size to 1.8rem but set the `line-height` to `2rem` (which means 20px on my phone, instead of 25) and it will look fine.
Doing that you also need to modify the [avatar margin](https://github.com/diaspora/diaspora/blob/1fdc17d96cf5190a9e9ac069510c1985608a7a58/app/assets/stylesheets/mobile/header.scss#L182) setting -5 to -7 to keep it aligned. This code is a little bit dirty I guess we should clean it. Apart from that the code looks good to me, so it should fine to merge once you corrected these remarks.

**Comment by Muhannes** [comment]
Ok, now it is fixed @Flaburgan.

**Review by Flaburgan — APPROVED** [review]

**Comment by Flaburgan** [comment]
@svbergerem this looks okay to me, do you want to merge it?

**Comment by svbergerem** [comment]
Merged as c5b133d3e86fb0a6a822588e31facdc6db6d37db. Thank you! :)

**Pull request closed without merging**
