### PR TITLE
fetch mentioned people if they don't exist locally yet

### LINKED ISSUE #4491: Mentions should fetch the profile if it doesn't exist locally yet
I thought we had that functionality, but apparently we don't.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/871269-mentions-should-fetch-the-profile-if-it-doesn-t-exist-locally-yet?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by SuperTux88**
fixes #4491 
supersedes #6793

### CODE REVIEW

**Comment by cmrd-senya** [comment]
Just was going to work on #6793. Well, okay than.

**Comment by SuperTux88** [comment]
I already fixed this by accident after reading this https://github.com/diaspora/diaspora/pull/6894#issuecomment-228735377 and then saw that you already have a PR for this and didn't create my own. But since your PR still have broken tests and we hopefully freeze "soon", I thought I could create a PR of this (because it was already finished).

But you can probably create another PR for your other drive-bys then.

**Comment by cmrd-senya** [comment]
Ah, it just required some rebasing (broken tests were there mostly because of the different issues fixed elsewhere, like #6795). Really, I was only one day late!

What do you mean by "drive-by"?

**Comment by jhass** [comment]
Thanks!

**Comment by SuperTux88** [comment]
@cmrd-senya you did something with gon and also changed the PeopleController, I didn't do this in my PR because it didn't base on yours, and this things have nothing to do with #4491 (that's why it is a "drive-by"). So if the gon-change is still needed you should create a new PR for this. Also I think the change in the PeopleController makes sense, so you probably create a PR for this.

**Comment by cmrd-senya** [comment]
>  you did something with gon and also changed the PeopleController,

Ah, I didn't quite recognize that you mean these changes.

Well, gon-change has already been merged within another PR (#6864). It was in #6793 because it was the reason of some failing tests with the changes. You didn't experience the failure because you worked on a develop branch with this commit merged already.

Another thing from PeopleController is small and insignificant, but, right, I can open a PR for that still.

**Pull request merged**
