### PR TITLE
Speed up asset serving in development

### PR DESCRIPTION
**Pull request by svbergerem**
[Discourse uses the same code](https://github.com/discourse/discourse/blob/master/lib/middleware/turbo_dev.rb) and this is just the gem version of it.

### CODE REVIEW

**Comment by Flaburgan** [comment]
What's the factor of gain?

**Comment by svbergerem** [comment]
I tried this with my own dev setup:

1. switch from turbo-dev-assets branch to develop branch
2. start server
3. load `/user/edit`
4. reload
5. reload after small change:
  ```diff
diff --git a/app/assets/stylesheets/settings.scss b/app/assets/stylesheets/settings.scss
index e51edfd..0d894b8 100644
--- a/app/assets/stylesheets/settings.scss
+++ b/app/assets/stylesheets/settings.scss
@@ -19,7 +19,6 @@
 }
 
 .profile-photo-upload {
-  text-align: center;
 
   .avatar {
     height: auto;
  ```
6. reload after change affecting more lines of code
  ```diff
diff --git a/app/assets/stylesheets/color-variables.scss b/app/assets/stylesheets/color-variables.scss
index f0ee287..d337088 100644
--- a/app/assets/stylesheets/color-variables.scss
+++ b/app/assets/stylesheets/color-variables.scss
@@ -25,7 +25,7 @@ $light-green: lighten($green, 20%);
 $red: #a80000;
 $blue: #3f8fba;
 
-$sidebars-background: #f0f0f0 !default;
+$sidebars-background: #000 !default;
 $sidebars-sub-background: darken($sidebars-background, 12%) !default;
 $left-navbar-drawer-background: darken($sidebars-background, 6%);
  ```
7. stop server

Then I did the same after switching from develop to turbo-dev-assets. Here are the results:

    develop
    initial      00:59:50
    reload       00:23:83
    small change 00:42:68
    big change   00:43:07 
  
    turbo-dev-assets
    initial      00:22:19
    reload       00:09:24
    small change 00:31:64
    big change   00:30:21

**Comment by Flaburgan** [comment]
The initial startup is the most impressive. It's a nice improvement anyway :) Thank you! I was personally mainly working directly inside Firefox without reloading the page because of that slowness.

**Comment by jhass** [comment]
Merged as 9eb0dddb1adef3307ee5ea1a29258731778e5e67

Thanks!

**Pull request closed without merging**
