### PR TITLE
Install ghostscript into the CI environment.

### PR DESCRIPTION
**Pull request by skyschub**
Let's see if this fixes the [current cucumber brokenness](https://github.com/diaspora/diaspora/runs/1851101000?check_suite_focus=true#step:10:1421).

### CODE REVIEW

**Comment by denschub** [comment]
Cukes passed with `ghostscript`, but jasmine timed out. Let's try one more time, this time using just all deps from the wiki (so that we have a documented environment), and let's also disable `fail-fast`. It's not worth the hassle to re-trigger things if one component fails, and we might get useful insights from not cancelling.

**Comment by denschub** [comment]
Build is green, let's :shipit:.

**Review by SuperTux88 — APPROVED** [review]
LGTM :cookie:

**Comment by denschub** [comment]
Merged as 7a7c48a470012ddfc426066da3549aa717da6b7c and 875f54b8460b660ec719aae5d4982cf5e83f7293.

**Pull request closed without merging**
