### PR TITLE
Add location and polls to mobile website

### PR DESCRIPTION
**Pull request by svbergerem**
This just adds them to the stream and the SPV. You are still unable to create a post with locations and polls from the mobile website. Voting is also not possible. This PR just implements the basics. Everything else should happen in other PRs.

### CODE REVIEW

**Comment by jhass** [comment]
Looking good, maybe a cuke that asserts that they're displayed?

**Comment by jhass** [comment]
Thank you!

**Comment by jaywink** [comment]
@svbergerem https://iliketoast.net/posts/681449 any ideas why?

**Comment by svbergerem** [comment]
@jaywink Thank you for the quick bug report. That was kind of a silly mistake. #6249 should fix this.

**Pull request merged**
