### PR TITLE
only require "fog/aws"

### PR DESCRIPTION
**Pull request by ghost**
This slightly reduces memory footprint by only requiring `fog/aws` instead of the full `fog` gem.

```
Before: 87.1523 MiB
After: 84.7461 MiB
```

### CODE REVIEW

**Comment by Flaburgan** [comment]
I was even thinking about dropping aws support completely, as far as I know joindiaspora was the only pod using it and I'm not sure it still works as we didn't test it for a while.

**Comment by jramos** [comment]
I'm using it. I've noticed old profile photos aren't deleted when they're replaced, but otherwise it seems to work.

**Comment by svbergerem** [comment]
> If there's a metagem available for your cloud provider, e.g. fog-aws, you should be using it instead of requiring the full fog collection to avoid unnecessary dependencies.

(https://github.com/fog/fog#dependency-notice)

**Comment by SuperTux88** [comment]
We use `asset_sync` and that gem has still `fog` as dependency :(

See: AssetSync/asset_sync#325

**Comment by svbergerem** [comment]
@SuperTux88 Thanks. :(

**Comment by SuperTux88** [comment]
Merged as 43b1632148c17106752753abb0ee40337b478a16

Thank you!

**Pull request closed without merging**
