### PR TITLE
Do not display chat on small devices

### PR DESCRIPTION
**Pull request by ghost**
It happens to me a lot, on mobile to accidentally open the chat. I think it should not be displayed on small screens.

### CODE REVIEW

**Comment by Flaburgan** [comment]
It would be nice to not load it at all to limit js download and execution on mobile.

**Comment by AugierLe42e** [comment]
I guess it's time to bring @Zauberstuhl to the conversation.

**Comment by Zauberstuhl** [comment]
> It would be nice to not load it at all to limit js download and execution on mobile.

https://github.com/diaspora/diaspora/blob/develop/app/views/streams/main_stream.html.haml#L7

If you toggle mobile view the jsxc should be not included.

**Comment by AugierLe42e** [comment]
> If you toggle the mobile view jsxc is not included.

No, he meant, on desktop view, but seen from a mobile.

**Comment by denschub** [comment]
Sorry, I'm going to close this one. The chat is not included in our mobile view, and the non-mobile responsive view is called "Desktop version" for a reason. Excluding features in the mobile version is the reason people switch over to the desktop version, and if we exclude features there, people will yell at us.

We could discuss about making a less obtrusive version for smaller screen resolutions, for example just a little speech bubble in the corner, but removing it entirely is not an option for me, and nobody else merged this yet, so.. closing.

**Pull request closed without merging**
