### PR TITLE
Issue #6137: Add focus:not(:hover) color

### PR DESCRIPTION
**Pull request by morashid92**
Thanks for pointing me towards the workflow page @jhass. And i've also linked my account with my commits. Now back to CSS. This commit changes the hover away color of the .dropdown instead of .nav-badge which I think is convenient.

### CODE REVIEW

**Comment by svbergerem** [comment]
Now you have the consistency and accessibility issues that I mentioned in #6137. There is no way to see if the bell icon is focused and all other links in the header will be white on focus except for the bell icon.

Also please use a color variable. I guess in this case [`$navbar-inverse-link-color`](https://github.com/diaspora/diaspora/blob/develop/app/assets/stylesheets/bootstrap-variables.scss#L399) would be the correct one.

**Comment by morashid92** [comment]
Ok, i've changed hex to the variable now. Also, so your suggesting that .nav-badge should be used instead then?

**Comment by svbergerem** [comment]
For consistency you would have to add the color to all links in the header, so maybe something like
```scss
.navbar-nav > li > a:focus:not(:hover) { ... }
```

**Comment by svbergerem** [comment]
@morashid92 why did you close this PR? :-(

**Comment by morashid92** [comment]
@svbergerem Whoops, I was creating another fix which I thought had to do with this, but came to an understanding that its browser related. Not any more it isn't!

**Comment by denschub** [comment]
Ping?

**Comment by svbergerem** [comment]
#6137 has been closed. Thanks for your work.

**Pull request closed without merging**
