### PR TITLE
Using original size for pictures in gallery on desktop view

### PR DESCRIPTION
**Pull request by ghost**
The counterpart of abandonning `stretchImages` option in  #6536 is that pictures are now really small in gallery. I think the gallery on desktop view should display the photo in its original size.

### CODE REVIEW

**Comment by AugierLe42e** [comment]
I've open a Loomio thread to discuss this PR: https://www.loomio.org/d/4U2vwQgW/ideas-regarding-pictures

**Comment by AugierLe42e** [comment]
Ping?

**Comment by svbergerem** [comment]
I agree that the large thumbnail is too small in some cases but the original image could be huge and the user won't be able to find out before they open the gallery.

**Comment by AugierLe42e** [comment]
So a solution could be to add another image size.

**Comment by svbergerem** [comment]
Someone on the IRC mentioned that fixing #6649 first could be a nice compromise. Then users are still able to see the large thumbnail and after clicking on the big image they will see the original size.

**Comment by svbergerem** [comment]
I just checked this again and we don't use the large thumbnails, but `scaled_full` which is resized to `[700, nil]`. I think that's good enough and will close this PR. Whoever disagrees with me can still open a new issue.

**Pull request closed without merging**
