### PR TITLE
Design for the aspect dropdown in the publisher

### PR DESCRIPTION
**Pull request by ghost**
Before :

dropdown0

after :

dropdown

### CODE REVIEW

**Comment by Raven24** [comment]
not bad, but I'm not sure the button should be the same width as the contents. I somewhat like the "minimal" width.

**Comment by Flaburgan** [comment]
Yeah this can probably break the design is someone has anaspectwithaverylongnamelikethat.

**Comment by jhass** [comment]
Yeah, me too. What I would consider changing is aligning the left side with the button instead of the right side though.

**Comment by AugierLe42e** [comment]
Yeah, I wanted to ask you advice on this one. Problem is : BS dropdown requires the following structure :

    <div class="btn-group">
        <button class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            Dropdown button
        </button>
        <ul class="dropdown-menu">
            
        </ul>
    </div>

I don't know how to set the `width` property of the `<div>` element to be equal to the `width` property of the `<ul>` element which has it's own width.

I could, as @jhass says, changing the aligning of the list and let the width unfixed. Problem is the following :

dropdown-problem1

Which makes it elegant if the user has a very long aspect name but inelegant if not :

dropdown-problem

Here is what I think : given that, anyway, the number of chars available for an aspect name is 20, let's adapt the width to that maximum width ?

**Comment by jhass** [comment]
Huh? I literally mean just changing the alignment, still keeping the round borders at the top.

**Comment by AugierLe42e** [comment]
I personnally don't like the BS' default space between the button and the dropdown. I find it visually illogic.

**Comment by AugierLe42e** [comment]
Here is my other proposition :

dropdown

With a fixed width set to the maximum with (for a 20 chars aspect name).

**Comment by jhass** [comment]
It still looks too big to me tbh, to much empty space in the button.

**Comment by AugierLe42e** [comment]
> It still looks too big to me tbh, to much empty space in the button.

This is how it will look if someone has a very long aspect name anyway.

**Comment by jhass** [comment]
With that long aspect name it won't have as much empty space though.

Can we maybe achieve something like this? (Rough mockup, but you get the idea):

aspect_mockup

**Comment by AugierLe42e** [comment]
I find this really ugly :/

**Comment by jhass** [comment]
I didn't mean to do a pixel perfect version of how it should look like, just demonstrating the idea, use your imagination!

**Comment by AugierLe42e** [comment]
My imagination tells me it's not a good way. It looks really weird to me to have a button that is not the width of the dropdown.

Otherwise, the only solution I see is a bit of JS to dynamically adapt the button to the width of dropdown:

    var width = $('.dropdown-menu').show().css('width');
    $('.btn-group').css('width', width);

**Comment by Flaburgan** [comment]
>It looks really weird to me to have a button that is not the width of the dropdown.

This is how the blueprint dropdown was though.

**Comment by AugierLe42e** [comment]
> This is how the blueprint dropdown was though.

And I found it ugly :p
TBH, I started #5480 because I found it ugly too, espacially the dropdown.

**Comment by AugierLe42e** [comment]
And what about this modified padding ?



I think leave some space in the button is not that bad. It is vsually ventilated.

**Comment by AugierLe42e** [comment]
Ok, here is my last proposition, dynamic width computed with a bit of JS code :

drpdwn1

And with  very long aspect name :

drpdwn2

I have nothing more to propose :(

**Comment by goobertron** [comment]
I also don't like the over-long button, I'm afraid. Buttons should be only as long as necessary for the text contained within them, unless there's a very good reason to make a button longer. Having the drop-down longer than the button is no problem to me.

**Comment by jhass** [comment]
Yeah, still no improvement to me either I'm afraid.

**Comment by AugierLe42e** [comment]
Hmm... It seems like we are in a dead end :/

**Comment by AugierLe42e** [comment]
Can this be merged ?

dropdown

**Comment by Flaburgan** [comment]
@AugierLe42e the aspect dropdown is also used in hovercards and on the profile page. So this PR brings inconsistency. 

If the box expands to the left and not to the right like you suggest, it's because the button is placed on the right of the profile page. So, someone with big aspect name would see the dropdown cut by the end of the screen if it was shown at the right instead of left like it is now.

**Comment by AugierLe42e** [comment]
Ok, closing it so.

**Pull request closed without merging**
