### PR TITLE
Very minor changes to graphics

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jhass** [comment]
Uhm, why?

**Comment by RyDroid** [comment]
It is a bit lighter and easier to understand without a GUI + HTTPS > HTTP for privacy.

**Comment by jhass** [comment]
I doubt anybody wants to edit any of this by hand, the next edit to them will just readd tags like that, so it's unnecessary code churn.

If you want the URLs fixed you should make that effort in the editors generating them.

**Comment by RyDroid** [comment]
Some URLs are generated by an Adobe proprietay program, so it is impossible to fix except by working in Adobe.

**Comment by jhass** [comment]
"that effort" = submitting an issue to them.

**Comment by Flaburgan** [comment]
There are tools to automatically strip comments and compress svg files to make them lighter. It would be nice to see that applied on our image files.

**Comment by jhass** [comment]
We're not using graphics/ as material on the website but rather as source material to generate things from that are possibly used on the website.

**Pull request closed without merging**
