### PR TITLE
Left and right navbar polishing

### PR DESCRIPTION
**Pull request by ghost**
Supersedes #6112 and #6113.

### CODE REVIEW

**Comment by jhass** [comment]
Shouldn't we have this mergable together with #6113 ?

**Comment by AugierLe42e** [comment]
Can be. But @pablocubico choosed to open two separated PRs so I just tried to resolve the one that was failling. I'll try to resolved the rest of failling tests tonight.

**Comment by svbergerem** [comment]
I agree with @jhass. It would be great if you could add the changes from #6113 since we want to merge both at the same time so running the tests for a combined PR and merging that afterwards would be nice.

**Comment by AugierLe42e** [comment]
I'm ok with it. Meanwhile, can someone help me with [this test](https://travis-ci.org/diaspora/diaspora/jobs/74964930#L1392)? It's the last failing one. It's a bit weird.

**Comment by pablocubico** [comment]
Thanks for taking the lead on this, Augier! I'm under a big pile of work
and looking for a new house so I'll have no time this week.

**Comment by AugierLe42e** [comment]
#6113 has been merged here. There's now only two failling tests left. I'll try to solve them tonight but if you can, @svbergerem, take a look at them, I'll be glad.

**Comment by AugierLe42e** [comment]
I need help on the cucumber failing tests. They seem to be complitely random but still happen at least once. I ran `features/desktop/posts_from_main_page.feature` three times on my computer, I got the three following different results:

```
Failing Scenarios:
posts_from_main_page.feature:21 # Scenario: expanding the publisher
```
```
Failing Scenarios:
posts_from_main_page.feature:154 # Scenario: change post target aspects with the aspect-dropdown before posting
posts_from_main_page.feature:169 # Scenario: post 2 in a row using the aspects-dropdown
```
```
Failing Scenarios:
posts_from_main_page.feature:57 # Scenario: post a text-only message to just one aspect
posts_from_main_page.feature:157 # Scenario: change post target aspects with the aspect-dropdown before posting
posts_from_main_page.feature:172 # Scenario: post 2 in a row using the aspects-dropdown
```

Though, it's always the same set of instruction causing problem:

```
When I am on the aspects page
And I select all aspects
```

It seems like the redesign slowers something causing Capybara failing randomly more ofter than usually.

**Comment by svbergerem** [comment]
These tests were randomly failing on my dev pod yesterday. (while testing this PR) The aspect selection was wrong after reloading the page. In the tests we select only one aspect, reload the aspects page and try to select all aspects but when the cukes failed all aspects were already selected.

**Comment by AugierLe42e** [comment]
Yesn that's exactly what I saw. This is a bit weird because this PR has very few JavaScript. It could be Backbone-related. I'd be glad if you have the time to examine this.

**Comment by Flaburgan** [comment]
I just tested this locally, it looks good to me. The .col-md-3 .col-lg-2 on #left-nav-bar is weird because the width becomes bigger when the screen becomes smaller, but col-md-2 is too small for aspect names so I think it's good enough.

**Comment by AugierLe42e** [comment]
Yep. But still have a test failing and I can't figure out why :/

**Comment by AugierLe42e** [comment]
Nice! Tests finally pass! Though I'm not sure why...

**Comment by svbergerem** [comment]
new aspect modal

Maybe move the modal outside of the `.hoverable`:
```diff
diff --git a/app/assets/javascripts/app/views/aspects_list_view.js b/app/assets/javascripts/app/views/aspects_list_view.js
index d6575e3..3211328 100644
--- a/app/assets/javascripts/app/views/aspects_list_view.js
+++ b/app/assets/javascripts/app/views/aspects_list_view.js
@@ -31,7 +31,7 @@ app.views.AspectsList = app.views.Base.extend({
   },
 
   appendAspect: function(aspect) {
-    $("#aspects_list > *:last").before(new app.views.Aspect({
+    $("#aspects_list > .hoverable:last").before(new app.views.Aspect({
       model: aspect, attributes: {'data-aspect_id': aspect.get('id')}
     }).render().el);
   },
diff --git a/app/assets/templates/aspects-list_tpl.jst.hbs b/app/assets/templates/aspects-list_tpl.jst.hbs
index 9883ad5..63c3483 100644
--- a/app/assets/templates/aspects-list_tpl.jst.hbs
+++ b/app/assets/templates/aspects-list_tpl.jst.hbs
@@ -7,5 +7,5 @@
   <a href="#" class="selectable new_aspect" data-toggle="modal" data-target="#newAspectModal">
     {{ t "aspect_navigation.add_an_aspect" }}
   </a>
-  <div id="newAspectContainer"></div>
 </li>
+<div id="newAspectContainer"></div>
```
It might be that you will have to adapt some tests.

**Comment by AugierLe42e** [comment]
> It might be that you will have to adapt some tests.

Seemingly not.

**Comment by svbergerem** [comment]
@AugierLe42e @pablocubico Thank you! :)

**Comment by pablocubico** [comment]
Thank you guys! Glad to see this merged!

**Comment by Zauberstuhl** [comment]
@pablocubico could you check #6341? thanks

**Pull request merged**
