### PR TITLE
Rails 4.2

### PR DESCRIPTION
**Pull request by jhass**
One deprecation warning left, coming from fixture_builder. Didn't run cucumber yet, let's see what Travis says.

<del>diaspora-vines needs a release /cc @zauberstuhl</del>

### CODE REVIEW

**Comment by svbergerem** [comment]
@jhass Is there an easy way to get rid of the deprecation warning?

**Comment by jhass** [comment]
Didn't look into it, but if it's that much of an issue for anybody, the way to go would be fixing it upstream and pulling in the fix as a monkey patch until there's a new upstream release with the fix.

**Comment by svbergerem** [comment]
Oh ok, you already opened an issue upstream: https://github.com/rdy/fixture_builder/issues/30 Looks like there isn't much activity on that repo :-\

**Comment by jhass** [comment]
Yeah, unfortunately not.

**Comment by jhass** [comment]
Slayed the newly randomly failing spec and added some more fixes.

Now really the only thing left is a deprecation warning from fixture_builder. Either this will be patched upstream very soon and we only have live with it for a short time, or this would be delayed forever just because of that, therefore I'd vote to ignore it for this PR.

**Comment by svbergerem** [comment]
@jhass There is still no answer from upstream so I'd say we just merge this. I guess this PR could need a rebase. @denschub could you review and merge this PR afterwards?

**Comment by jhass** [comment]
k, rebased.

**Comment by jhass** [comment]
Rebased.

**Comment by goobertron** [comment]
Cool! <3

**Comment by denschub** [comment]
Looks good to me, tests are green. Will merge.

**Pull request merged**
