### PR TITLE
Show aspects when hovering a post's scope

### PR DESCRIPTION
**Pull request by taratatach**
Fix issue #3181
- Show "The whole Internet" for public posts
- Show "Nobody" for non public posts without any aspect
- Show the aspects list otherwise

### CODE REVIEW

**Comment by svbergerem** [comment]
@jhass Would something like "Chosen audience: Public/All aspects/Family, Work" improve the issue?

**Comment by Flaburgan** [comment]
@svbergerem or maybe re-add the date next to the aspect name? To be honest, I would love to see the ability to see old posts when a new contact is added to an aspect... (That would mean send him every posts in that aspect which could be a lot, but I'm sure we could find a workaround).

**Comment by jhass** [comment]
@svbergerem I don't think so tbh.

**Comment by denschub** [comment]
Open issues, an unresolved UX mystery and a horrible merge conflict list. I'll close this. Feel free to continue (or better, start over) if you feel strong about it. In any case, if someone is really interested in working on this, I suggest starting a discussion on loomio first.

Closing this PR for cleanup purposes. Thanks for your work!

**Pull request closed without merging**
