### PR TITLE
Adjust the SPV design

### PR DESCRIPTION
**Pull request by svbergerem**
spv1
spv2
spv3

### CODE REVIEW

**Comment by Flaburgan** [comment]
Maybe the reshares / likes and comments counts should also be wrapper in a `.framed-content`?

Also, I'm wondering about the size of each column. In the other views, the post is in a col9 where here it only has a col6, which is weird because the SPV is where you go when you want to focus on a special post. So to have more space for it when it's lost in the stream than when you focus it seems wrong. In another hand, we sometime have small post but big comments, so to reduce the comment is maybe not the solution... I'm kinda lost here.

**Comment by AugierLe42e** [comment]
> Maybe the reshares / likes and comments counts should also be wrapper in a .framed-content?

+1

**Comment by denschub** [comment]
> In another hand, we sometime have small post but big comments, so to reduce the comment is maybe not the solution... I'm kinda lost here.

Yeah, right. I still feel like 50/50 is a somewhat suitable approach. Maybe something like 60/40 on large screens.

> Maybe the reshares / likes and comments counts should also be wrapper in a .framed-content?

Actually, I've tried that locally with Steffens changes and we had a small chat about this. Thouse counters will look pretty lost in their own white box, which does not look nice either. I also had the idea of "reusing" the notification badge in some way, but that's not possible since we would have no way of showing the faces.

Not too sure about this. While this PR is something I could live with, I have a hard time finding a "*perfect*" solution...

**Comment by svbergerem** [comment]
spv1_2
spv4_2

**Comment by denschub** [comment]
Hm. Looks cleaner. Other opinions?

**Comment by Flaburgan** [comment]
I'd say go for it and we'll see if better ideas pop out :)

**Comment by AugierLe42e** [comment]
I'm ok with that.

**Comment by denschub** [comment]
Common consent, what a rare occasion. Merged. Thanks everybody!

**Comment by Flaburgan** [comment]
Just merged it in d-fr. It looks like we miss some padding-top:
capture du 2016-02-23 12-10-49
I would add at least put a 15px padding-top to `.head` to have the same space than the left one. And same opinion about the interaction div.

Also, I feel like the interaction avatars should not go under the like / reshare counts but stay aligned:
capture du 2016-02-23 12-11-18

**Comment by denschub** [comment]
Padding [is fine on a clean develop branch](https://cloud.githubusercontent.com/assets/344777/13250113/678c4e74-da28-11e5-8f00-6ff88afde9a6.png) so that's probably your issue. Good idea regarding the faces, though.

**Comment by svbergerem** [comment]
@Flaburgan Like this?
SPV alignment

**Comment by Flaburgan** [comment]
@svbergerem yes :)

**Pull request merged**
