### PR TITLE
Basic changes for italian translations

### PR DESCRIPTION
**Pull request by faghy**
Fixed errors in the locales folder that caused missing elements in the app display when the user was logged in, by setting DEFAULT_LANGUAGE = "it". Translated javascript.it.yml in the javascript folder and added the missing necessary strings in it.yml inside the diaspora folder

### CODE REVIEW

**Comment by denschub** [comment]
Hi! Thanks for your willingness to contribute. Unfortunately, we cannot accept this PR.

[As documented here](https://wiki.diasporafoundation.org/Contribute_translations), we use an external tool, webtranslateit, for translations. We do this for a couple of different reasons, like having discussions about specific strings, an easier-to-use history, as well as allowing people without technical skills to translate.

Sadly, pushing your updates to WebTranslateIt would be quite a big pain, so I have to ask you to enter your translations there. We regularly pull those updates, so your changes will automatically be included in a future release.

**Comment by faghy** [comment]
ok, thanks, please know that if someone sets the DEFAULT_LANGUAGE to Italian in initializers/locale.rb with the current files the application does not load the header and menus when the user is logged in, so it is a application bug, in fact our newly created https://diaspo.it pod is currently the only one in Italian language: https://diaspora.fediverse.observer/diaspo.it

**Comment by denschub** [comment]
This is hardly a bug, as you're not supposed to change anything outside the configuration files we designed. diaspora\* automatically detects the user's browser language and sets that as the profile language, and if you don't touch with our implementation code, diaspora\* will just fall back to the English strings whenever something isn't translated to Italian.

**Comment by faghy** [comment]
ok, what I don't understand is why the algorithm of fediverse.observer where you report the pod did not detect our pod in Italian, but in English. After changing DEFAULT_LANGUAGE (or something else that I don't know) it correctly detected the Italian language. I am aware that the correct value is EN and the translations are loaded automatically based on the user's language and where they do not exist the fallback is inserted, but we liked to emphasize to the users that our pod is for Italians and to make known the social and the philosophy of our country. In any case, thanks for your availability.

**Pull request closed without merging**
