### PR TITLE
#7967 clarify multiple reshares [WIP]

### PR DESCRIPTION
**Pull request by ghost**
Adressing the issue #7967 .

I would say that there is still some work to do. But it would be nice to have revisions already.

Some points of attention:

-I changed the "reshare_by" logic to "reshare_of". This means that, instead of refering to the reshared post as a "Reshare by ${user}#, it now reads "reshare of **original post title**".

-The **original post title** is a link to the original post. If the original post is deleted, this link turns into plain text.

-Specs where updated.

-I need to make some experimentation on the UI to see how things behave. But I imagine that, when someone likes the reshared post, the notification reads something like "(person) liked your post reshare of (original title)". At first I would add logic to the translations so that "post" turned into "reshare", instead of "post reshare", but it turns out to work well with simpler code in the english language, as a "post reshare" means the same thing as "reshare", but less code is required. But this might be a problem in other languages.

-I should make manual tests and think about what happens when someone reshares a reshared post.

-Although all tests passed, I should pay more attention if code elsewhere could be broken by the changes. Maybe a test missed something important.

### CODE REVIEW

**Comment by HankG** [comment]
This looks like a good start to what you are trying to achieve.  I'd like to play around with this to see what it looks like side by side but appreciate the way you are attempting to tackle this.  Thanks!

> -Although all tests passed, I should pay more attention if code elsewhere could be broken by the changes. Maybe a test missed something important.

Looking at the CI it seems there are Cucumber tests that need to be addressed.  It's bombing out on the behavior of a deleted post.

**Comment by goobertron** [comment]
Thanks for working on this.

I envisaged the notification being

> X has interacted on your reshare Original post title

rather than

> X has interacted on your post Reshare by you

That means detecting whether the post concerned is a reshare; and, if so, replacing 'post' with 'reshare'. Otherwise the notification will read 

> X has interacted on your post reshare of Original post title

which looks somewhat clunky and is longer, so might not fit well in the notifications drop-down or page.

Is that something you could do? It looks as though you are already detecting whether or not the post is a reshare, so hopefully this would be feasible.

**Comment by davidmoseler** [comment]
It is feasible. I just need to create a new key in I18n for the interactions on reshared posts. A new key is probably necessary because the wide range of grammars in the languages supported by diaspora.

**Comment by davidmoseler** [comment]
I thought about using a variable like "post_type" to distinguish between "post" and "reshare". I even wrote the code, but then I erased it for some reason. Maybe because I will need to change all calls to all of these translations anyway. But maybe this is the best way to do it.

**Comment by goobertron** [comment]
As there is already an `if post.is_a?(Reshare)` query, I think all you'd need to do is to tell it there to change the word 'post' to 'reshre' in the notifications strings.

That is, if that line 12 in `app/helpers/posts_helper.rb` isn't used in any other parts of the app. If it is, doing this might have undesired effects elsewhere. Hope you can find that out easily.

**Comment by denschub** [comment]
We had some discussions about reshares and identified more need for further discussions. :) We will be having a long chat about how reshares work in the future, and we will make sure to include the points raised here. Thanks much! :)

**Pull request closed without merging**
