### PR TITLE
Rewrite hover effect on conversations with multiple participants in css

### PR DESCRIPTION
**Pull request by lislis**
We noticed that the sliding effect on conversations with a lot of participants has kind of poor performance. I rewrote the effect in css which looks way smoother and isn't that annoying once you have a lot on these conversations.  
I had to cherry pick the commit from another fork and adjust it to a backbone refactor. Sry for the weird git things, it made me go crazy.  
Opinions and suggestions welcome :D

### CODE REVIEW

**Comment by jhass** [comment]
Looks nice! If you could just indeed clean up the git history a bit? `git checkout rewrite-conversation-hover-in-css; git rebase -i e2a5912;`, there choosing squash for your last two commits and then just `git push -f origin rewrite-conversation-hover-in-css`.

**Comment by svbergerem** [comment]
Great! :) Unfortunately conversations with more than 2 participants now have a bigger bottom-margin. It would be great if you could fix that.

**Comment by lislis** [comment]
@svbergerem  ha you're right :) I just assumed everything uses border-box. I pushed the fix

**Comment by svbergerem** [comment]
Awesome, the hover effect feels much more mature with this PR. Thank you! :)

**Comment by lislis** [comment]
Yaay!

**Comment by goobertron** [comment]
Thanks a lot, @lislis!

**Comment by Flaburgan** [comment]
Thank you!

**Pull request merged**
