### PR TITLE
Issue #5884: Added link to diasporafoundation.org to invitation email

### PR DESCRIPTION
**Pull request by ghost**
I've added a P.S. with the url at the end of the invitation email in en.yml. (please reject freely)

### CODE REVIEW

**Comment by efstrian** [comment]
It seems my en.yml wasn't OK. (2 lines incorrectly deleted)

**Comment by denschub** [comment]
Could you please squash your three commits into a single one?

**Comment by efstrian** [comment]
Done! Could someone note what 'app/views/devise/mailer/invitation_instructions.markerb' exists for?

**Comment by denschub** [comment]
Thanks, merged as 63be9d57b601ab5ea37876ac6b7e5e97097b41fd.

**Pull request closed without merging**
