### PR TITLE
Fix for Empty input field when editing aspect name

### LINKED ISSUE #6548: Empty input field when editing aspect name
When editing an aspect name, the first rename works fine.
If I then try to edit the name again (without reloading the page), the input field is empty.
Also, it would be nice to have a **Cancel** button or something to undo an active edit.

Reproduce:
---
1. Open any aspect.
2. Rename aspect (clicking on the pen icon, changing the name, clicking **Update** button).
3. Try to rename again and find that the input field is blank.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28271422-empty-input-field-when-editing-aspect-name?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sarithats**
Fix #6548

### CODE REVIEW

**Comment by svbergerem** [comment]
Thanks! It would be great if you could write [a jasmine test](https://github.com/diaspora/diaspora/blob/develop/spec/javascripts/app/pages/contacts_spec.js#L74) for your PR.

**Comment by svbergerem** [comment]
@sarithats Any news? Do you need some help to write the tests?

**Comment by sarithats** [comment]
@svbergerem Sorry, I don't know how to write jasmine test; and I didn't spend time for this.

**Comment by svbergerem** [comment]
@sarithats Would you like some help or do you think someone else should write the tests?

**Comment by denschub** [comment]
Superseeded by #6706 which I just merged.

**Pull request closed without merging**
