### PR TITLE
Enlarge accept and deny buttons in open-id authorization

### LINKED ISSUE #8170: v0.8: On Grant Access Screen the Accept / decline buttons are way too small
Can you make these buttons "Ablehnen" / "zulassen" (on mobile browsers) much bigger?

Screenshot is from iPhone 11

IMG_3650

### PR DESCRIPTION
**Pull request by tclaus**
Will fix #8170 
New appearance: 
Simulator Screen Shot - iPhone 11 - 2020-11-06 at 13 40 29

### CODE REVIEW

**Comment by jhass** [comment]
Screenshot 2020-11-09 at 12 07 16

Mmh, might be better to keep them close together for desktop's sake?

**Comment by tclaus** [comment]
Better right side or left side?

**Comment by jhass** [comment]
We've been sticking to the right side for most of our buttons so far IIRC.

**Comment by tclaus** [comment]
🤔
Imaging the red button next to the blue - sticked on the right side - far, far away from the left aligned 'special' content. 
I suggest to center the buttons? 
Bildschirmfoto 2020-11-09 um 19 07 16

On simulated mobile: 
Bildschirmfoto 2020-11-09 um 19 17 36

Is this OK?

**Comment by jhass** [comment]
Why not like this?

```

+-------------------------------------------------------+
|                                                       |
+-------------------------------------------------------+
|                                                       |
|                                                       |
|       +--------------------------------------+        |
|       |                                      |        |
|       |                                      |        |
|       |    +-------------+                   |        |
|       |                                      |        |
|       |     +-------+                        |        |
|       |                                      |        |
|       |     +------+                         |        |
|       |                                      |        |
|       |     +---------+                      |        |
|       |                                      |        |
|       |                                      |        |
|       |                                      |        |
|       |                     +-----+  +-----+ |        |
|       |                     |     |  |     | |        |
|       |                     +-----+  +-----+ |        |
|       +--------------------------------------+        |
|                                                       |
+-------------------------------------------------------+

**Comment by tclaus** [comment]
Bildschirmfoto 2020-11-10 um 12 53 17
Bildschirmfoto 2020-11-10 um 12 53 26
Bildschirmfoto 2020-11-10 um 12 53 34

Commit #30a2d24 looks now like this (iPhone 8, iPad and Desktop)

**Review by jhass — APPROVED** [review]

**Pull request merged**
