### PR TITLE
#7841 Post Unlike sets status icon correctly

### PR DESCRIPTION
**Pull request by HankG**

### CODE REVIEW

**Comment by jeremyf** [comment]
👍

**Review by skyschub — CHANGES_REQUESTED** [review]
Given that this was broken without us noticing, this probably needs a test.

**Comment by HankG** [comment]
@denschub OK.

**Comment by HankG** [comment]
I've updated the unit test to capture the errant behavior as well as to be as robust as the one for "like".

**Comment by HankG** [comment]
Are there additional changes after my latest commit where I addressed the unit test or is something out of sync with the status?  I thought when I submitted new code it would reset the status with the new commit.  If I am looking at the main board view it looks like nothing has changed for two days and this needs changes, but in reality the PR changed a day ago and the new changes haven't been reviewed.  PS this is not meant as "why haven't the changes been reviewed?" this is a question about potentially stale status (or stale looking status) on the main PR view.

**Comment by HankG** [comment]
This is ready for review.

**Review by skyschub — APPROVED** [review]
Thanks for adding the test! :)

**Comment by denschub** [comment]
Merged!

**Pull request closed without merging**
