### PR TITLE
Add 'Be excellent to each other!' to the sidebar

### PR DESCRIPTION
**Pull request by svbergerem**
Be excellent to each other

### CODE REVIEW

**Comment by jhass** [comment]
Perhaps we should undo the collapsed items and always display them again?

**Comment by svbergerem** [comment]
Seems legit, done.

no collapsed sections

**Comment by Flaburgan** [comment]
Hm, I really liked them collapsed, it makes the ui clean and sober. What made you change your mind?

**Comment by jhass** [comment]
Well, the point of this is having something visible all the time. Having to uncollapse it first defeats it.

**Comment by Flaburgan** [comment]
So maybe it can be placed in the footer instead?

**Comment by AugierLe42e** [comment]
I really like them collapsed too. If you want to keep them uncollapsed, then there should definitely a option to hide that sidebar.

**Comment by jhass** [comment]
Being able to hide it, too, defeats  the point of having something visible all the time.

**Comment by SuperTux88** [comment]
Must the whole sidebar be always uncollapsed? Somehow I don't like the uncollapsed sidebar under the other sidebar (and it is really big on followed tags page), maybe move it back to the left side again?

**Comment by AugierLe42e** [comment]
> Being able to hide it, too, defeats the point of having something visible all the time.

There's no point in having something visible all the time for experienced users. I, for instance, have nerver had any use of this sidebar. It's just visual pollution for me.

**Comment by jhass** [comment]
This PR is not primarily about uncollapsing the sidebar, that was just done as a solution to the primary purpose.

**Pull request closed without merging**
