### PR TITLE
Invert button gradient

### PR DESCRIPTION
**Pull request by dimaursu**
Sorry, I messed this one up. I hope no other changes were introduced.

### CODE REVIEW

**Comment by Flaburgan** [comment]
Do you have the same rendering than 

in every browser?

**Comment by dimaursu** [comment]
webkit this is in webkit
firefox and firefox

**Comment by Flaburgan** [comment]
Looks ok for me. What about the sign in green button?

**Comment by dimaursu** [comment]
Looks good ;-)

**Comment by jhass** [comment]
Thanks again ;)

**Pull request merged**
