### PR TITLE
bump diaspora_jsxc to v0.1.2

### PR DESCRIPTION
**Pull request by ghost**
- adjust chat.scss diaspora container
- adjust back-to-top arrow
- load bower dep (moved from jsxc.dep.js)

### CODE REVIEW

**Comment by jhass** [comment]
This is targeted at Bootstrap 3 now, right?

**Comment by Zauberstuhl** [comment]
tested on develop branch yes

**Comment by Flaburgan** [comment]
@Zauberstuhl hm, is it a big work to also port it on the stable branch? It would be awesome to deliver chat improvements in a minor release, I know that some production pods enabled it.

**Comment by jhass** [comment]
Since the question is left unanswered I'm merging this only to develop for now.

**Comment by Zauberstuhl** [comment]
@jhass cheers. haven't tested it on stable yet.

**Pull request merged**
