### PR TITLE
"privacy aware" should be "privacy-aware"

### PR DESCRIPTION
**Pull request by GPhMorin**
Proof:
http://www.w3.org/2005/Incubator/socialweb/XGR-socialweb-20101206/
https://cs.uwaterloo.ca/~uhengart/publications/gis10.pdf
http://research.microsoft.com/pubs/152497/01main.pdf
http://www.amazon.com/Privacy-Aware-Knowledge-Discovery-Applications-Techniques/dp/143980365X

### CODE REVIEW

**Comment by denschub** [comment]
Such `README.md` improvements. Much grammar. Wow.

Sorry. Got caught by your profile picture for a moment. Thanks.

**Comment by maliktunga** [comment]
@denschub Isn't that obvious it's an Akita and not a Shiba Inu? ;-P

No problem!

**Comment by denschub** [comment]
I fear I have no clue about dogs. Looks kinda doge-y to me, though.

**Comment by maliktunga** [comment]
@denschub It's fine. They do have a lot in common! And anyway, that's a GitHub pull request discussion and not a discussion about canines, isn't it? ;)

**Pull request merged**
