### PR TITLE
Bump apparition to a commit to avoid warnings while running cucumber

### PR DESCRIPTION
**Pull request by Flaburgan**
Looks like apparition is now a dead project, at least they don't do any release but we want this fix so I'm bumping to a commit. See  https://github.com/twalpole/apparition/issues/81

### CODE REVIEW

**Comment by Flaburgan** [comment]
Hm. looks like the CI doesn't look this.

**Comment by tclaus** [comment]
What's about to switch to currently supported web driver cuprite? 
https://github.com/rubycdp/cuprite

**Comment by SuperTux88** [comment]
> Shouldn't we use a currently supported driver cuprite?

cuprite also isn't super active, there hasn't been a new release since over a year and we would have the same problem as with apparition because the current release of cuprite doesn't support dragging because the feature (https://github.com/rubycdp/cuprite/pull/176) isn't released yet. So at the moment we wouldn't have any advantage by switching. But whoever releases a new version first wins.

**Comment by SuperTux88** [comment]
Superseded by #8418

**Pull request closed without merging**
