### PR TITLE
Add new daily job to clean cache in public/tmp (as suggested in #5946).

### LINKED ISSUE #5946: public/tmp/ dirty image clean up
Images that are really code renamed as images are left in the public/tmp upload area after the system rejects them. Found a bunch when I was investigating an odd http call (unrelated it turns out). 
https://gist.github.com/dmorley/bfbe6c13f7570ebfbe63

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/14159752-public-tmp-dirty-image-clean-up?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by cmrd-senya**
fixes #5946

### CODE REVIEW

**Comment by denschub** [comment]
@cmrd-senya Do you mind fixing those whitespace errors raised by hound?

**Comment by cmrd-senya** [comment]
Sure I don't. Should I just make a new PR?

**Comment by Flaburgan** [comment]
You can push to this branch, it will update this pull request.

**Comment by jhass** [comment]
Merged as fe3ff10e07eb396ab6fa166d5f09885a05be615e

Thank you!

**Pull request closed without merging**
