### PR TITLE
Cleanup pending photos which were never posted with cronjob

### PR DESCRIPTION
**Pull request by SuperTux88**
Only delete photos older than a day, so we don't delete photos for posts which were uploaded 10 minutes ago and the author is still writing the post for it.

### CODE REVIEW

**Review by skyschub — APPROVED** [review]

**Comment by denschub** [comment]
@SuperTux88 specs are failing for MySQL 😞

**Comment by SuperTux88** [comment]
... and travis is finally green (after 3 hours of waiting for all builds to start and finish ...).

It wasn't MySQL, because on this PC I still have a MySQL dev env, but tests were green ... but I'm an idiot and I don't want to talk about it ;)

**Comment by denschub** [comment]
Ohhh, that was a good one! My approval is still valid. :)

**Comment by SuperTux88** [comment]
Merged as df4e79b842fa16b370c8c4b07b82bdd328f3ef7e

Thanks @denschub for the review :cookie:

**Pull request closed without merging**
