### PR TITLE
Remove photo export from settings

### PR DESCRIPTION
**Pull request by svbergerem**
It is not working so the link on the settings page is useless. This PR also removes some unused strings that are related to photo/profile export from the locales.

### CODE REVIEW

**Comment by goobertron** [comment]
Good idea. Is it worth trying to work on this? I'm wondering how useful a photo export will be, as they will be photos the user uploaded from their computer in the first place. I suppose it will be needed as part of an integrated seed migration tool, eventually.

**Comment by jhass** [comment]
Thanks!

**Comment by margori** [comment]
:-( I was going to implement this feature, fix bug #1802 

I see strange that this PR was merged without discussion, as @goobertron suggested, but whatever...

**Comment by svbergerem** [comment]
@margori I removed the button because it only said "Photo exporting currently unavailable". You can still fix the photo export and add the button once photo export is working again.

**Comment by margori** [comment]
you call, you get it. PR #5685 using zip files.

**Pull request merged**
