### PR TITLE
Add 'no posts yet' message to empty streams

### LINKED ISSUE #6852: on /tags pages when there is no asociated post found, there sould be a message stating that.
With 0.6 now there is a great indication that the site is searching for posts if you search for a tag.
but if it does not find any post with your searched tag the nice loading bar just disappears and nothing further happens.

there sould be a message like. "No posts found" ( for you to see on this pod) ^^

so people don't have to assume that but can be sure..

https://therealtalk.org/tags/lepetitprince
(example of empty post page)

I tested against realtalk beacause of 0.5.99

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/34931606-on-tags-pages-when-there-is-no-asociated-post-found-there-sould-be-a-message-stating-that?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by svbergerem**
Fixes #6852 and #5748.

stream
tags
profile

### CODE REVIEW

**Comment by jhass** [comment]
Thank you!

**Comment by paskalito** [comment]
thanks a lot :)

just wanted to ask if we really don't want to add the "( for you to see on this pod)"  to the message, since it is more correct and hopefully helps people to understand how federation works. (and could point people to search elswheren and then maybe find what theyre looking for.)

**Comment by svbergerem** [comment]
@paskalito "There are no posts yet. (for you to see on this pod)" sounds to me like the user won't be able to find posts on the pod. The message appears in the main stream, the tags stream, the mentions stream, the profile stream and so on.

Maybe "There are no posts in this stream yet."? "There are no posts for you in this stream yet."?

**Comment by jhass** [comment]
"There are no posts to display here yet."?

**Comment by paskalito** [comment]
### i think if possible there sould be diffrent messages for diffrent streams

Main stream > No Posts found! [as there is already a message with more explanation and this one is only to assure that there has been a search done]
Tags stream > No posts shared with you on this pod that contains #tag yet
Mentions stream > You haven't been mentioned yet
Profile stream > no posts shared with you yet
Aspects stream > No posts found! [as there is already a message with more explanation and this one is only to assure that there has been a search done]

on /contacts there is already a message

### And if there has to be one for all...
no posts for you found here  < that's my new favourite (but my brain is already going nuts)

There are no posts to display you here yet.?


### And maybe
A good soulution would als be a simple

**No Posts Found** message and then one or two lines below in grey and small.
(this can have the following resons)
- No one postet something with #tag
- Post is only shared in Aspects you're not a poart of
- the post has not been federated to this pod yet ( you can try searching on other pods)
- post may have been deleted


this way the message, "we have searched search is finished but theres is nothing here for you" would be communicatet pretty fast and clear. and there is for interested users some more information about why that is..

(also the "No post Found" could appear as simple centered text right in the place where the "searching" animation took place instead of a box where normally the search result would appear. would maybe be more accurate design language.)

**Comment by svbergerem** [comment]
There is also the liked, commented and activity stream and maybe others I didn't think about yet. Thus I prefered the "one message fits them all" solution and used the message @jhass proposed. You can see the changes in https://github.com/diaspora/diaspora/commit/1d58df13e34ec37b6b2bf77301b45eee41873823.

**Pull request merged**
