### PR TITLE
[WIP] Adds setting to define number of notifications per page

### PR DESCRIPTION
**Pull request by ghost**
This is still a raw work but the idea is here. Please tell me what you think of it.

screen shot 2015-08-28 at 23 06 43

### CODE REVIEW

**Comment by jhass** [comment]
-1 Too much configuration makes software harder to use, less polished for all possible configuration values and the code more complex.

**Comment by AugierLe42e** [comment]
I thought it would be conveniant for searching netofications.

**Comment by jaywink** [comment]
TBH, I'd rather have a search bar to search notifications. +/-0 for this.

**Comment by AugierLe42e** [comment]
Closing this, since it does not seem to have much success.

**Pull request closed without merging**
