### PR TITLE
Disable self-notification possibility

### LINKED ISSUE #6506: Receiving notifications for own comment on own reshare
Related to #6498

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27430029-receiving-notifications-for-own-comment-on-own-reshare?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by cmrd-senya**
fixes #6506

### CODE REVIEW

**Comment by jhass** [comment]
Please at least add a spec for this to https://github.com/diaspora/diaspora/blob/develop/spec/models/notification_spec.rb#L65

**Comment by cmrd-senya** [comment]
@jhass, is that enough?

**Comment by jhass** [comment]
Yeah, should be good enough.

**Comment by jhass** [comment]
Merged as 00588e1ef80e1dacb3a6178ab4304be22c20b22b

Thanks.

**Pull request closed without merging**
