### PR TITLE
🚑 Fix default aspects on profile page and bookmarklet publisher

### LINKED ISSUE #7679: Default sharing aspect functionality is not working from the user profile page
If one or multiple aspects are selected as the user default sharing aspect for posts (except the "All aspects" and "Public" options), the post is being shared to all the existing aspects of that user if it is published from his/her profile page.

Post publishing request bodies from homepage and profile page respectively: 
```
https://spyurk.am/status_messages

{"status_message":{"text":"test"},"aspect_ids":"2282","location_coords":"","poll_question":"","poll_answers":["",""]}
```

```
https://spyurk.am/status_messages

{"status_message":{"text":"test"},"aspect_ids":["2282","120","121","122","123","213"],"location_coords":"","poll_question":"","poll_answers":["",""]}

```
Tested on the following pods:
- spyurk.am
- diasp.eu

diaspora version - 0.7.1.1

### PR DESCRIPTION
**Pull request by SuperTux88**
Fixes #7679

### CODE REVIEW

**Review by skyschub — CHANGES_REQUESTED** [review]
Semi-Approved, but please remove the emojis from the commit messages, or at least move them to the end.

**Comment by SuperTux88** [comment]
Merged as 661b230ed213e4975d9d06e4f2907532cff552e5 and 0edf9ea48c7fda0e11bf921e6ef8d9d809dc8692 (without emojis)

Thanks for the review @denschub :) I think the world needs more emojis ... but when you don't like them you don't get an emoji-cookie ;)

**Comment by denschub** [comment]
... hey! I only dislike them in commit messages! I love them in comments! 😿

**Comment by SuperTux88** [comment]
OK 😻 🍪

**Comment by denschub** [comment]
💕

**Pull request closed without merging**
