### PR TITLE
Use Poltergeist instead of Selenium

### PR DESCRIPTION
**Pull request by svbergerem**
This PR uses [poltergeist](https://github.com/teampoltergeist/poltergeist/) for most cukes and updates Selenium. I kept selenium for the following cukes:
- <s>post preview with location, because poltergeist doesn't support geolocation (yet)</s>
- <s>mobile and desktop sign up with bogus data, because poltergeist doesn't support html5 form validation (yet)</s>
- <s>drawer cukes, because they where much more reliable with selenium</s>
- <s>download photos cuke, because poltergeist doesn't support file downloads (yet)</s>

Because poltergeist behaves different in some situations I also refactored some cukes and tried to improve them while doing that.

All cukes were green on my laptop. Let's see how this works on Travis.

### CODE REVIEW

**Comment by Flaburgan** [comment]
Just out of curiosity, what are the advantages to use poltergeist instead of selenium?

**Comment by svbergerem** [comment]
@Flaburgan Poltergeist uses PhantomJS and I hope that the cukes will be faster and have less random fails with PhantomJS instead of Firefox.

**Comment by denschub** [comment]
Poltergeist is headless.

**Comment by denschub** [comment]
Just for the record (I assume you already figured that out): some cukes are burning on Travis. However, the run time is impressive!

**Comment by denschub** [comment]
Nice! Finally, this passes. Thanks for your work and wheeee, fast cukes!

**Pull request merged**
