### PR TITLE
Fixes the header problem rendering statistics page

### PR DESCRIPTION
**Pull request by ghost**
Related to [this comment](https://github.com/diaspora/diaspora/pull/5464#issuecomment-71365544)

### CODE REVIEW

**Comment by jaywink** [comment]
Great, this fixes that issue. BUT, not sure if this was the case before, but the header is not rendering when *logged out*.

selection_048

**Comment by jaywink** [comment]
Yes it was visible before, I had the old test tab open :)

selection_049

After refreshing it, header disappeared.

**Comment by SansPseudoFix** [comment]
Doesn't works with mobile.

**Comment by AugierLe42e** [comment]
Should be better now.
When logged in :

screen shot 2015-01-25 at 13 27 17

When logged out :

screen shot 2015-01-25 at 13 28 07

Mobile view when logged in :

screen shot 2015-01-25 at 13 29 47


Mobile view when logged out :

screen shot 2015-01-25 at 13 29 03

**Comment by AugierLe42e** [comment]
Mobile view is ugly as boostrap isn't injected.

**Comment by jaywink** [comment]
Travis one build failed due to flaky not related test, so merging. Thanks for fixing this so fast!

**Comment by jaywink** [comment]
> Up to you to write some CSS now :p

LOL, missed this commit. But then, that beautification can be done separately - now it at least works :) IMHO the mobile page looks ok anyway even if the styling is different.

**Comment by AugierLe42e** [comment]
@jaywink : You're welcome, this was my fault. I didn't do the proper tests ;)

**Pull request merged**
