### PR TITLE
[WIP] Graceful unicorn restarts

### PR DESCRIPTION
**Pull request by ghost**
This allows unicorn to be restarted gracefully when `AppConfig.server.pid` is defined. E.g.

```
bin/eye restart web
```

### CODE REVIEW

**Comment by dmorley** [comment]
<3 I was just going to try and figure this out!

**Comment by jramos** [comment]
It isn't actually working. :-(  Still fiddling...

**Comment by SuperTux88** [comment]
If you are still working at something, you don't need to close it, you can add `[WIP]` to the PR-title, so we know we don't have to review that yet.

**Comment by jramos** [comment]
Well, I force pushed so can't reopen now, but good to know. :-)

**Comment by jramos** [comment]
@dmorley, new PR is here: https://github.com/diaspora/diaspora/pull/7217

**Pull request closed without merging**
