### PR TITLE
Refactor conversation creation

### PR DESCRIPTION
**Pull request by svbergerem**

### CODE REVIEW

**Comment by denschub** [comment]
Merged as 5c24714245b9a3f7d8707e92409db3c3d475d903, 0c995eb629c78e18337eecb12fd1c4557cbf14df and 80806ca58dc8ccd8ffc0e290e8b6963fa68cb98 and your contribution is appreciated, as usual!

**Comment by AugierLe42e** [comment]
Hey, you could have merged #7129 before doing this @svbergerem! It has been waiting for a month! >.<

**Comment by cmrd-senya** [comment]
A month? What do you know about waiting? :D

**Comment by svbergerem** [comment]
@AugierLe42e When you opened your PR I was already working on mine, finished my PR on the same day and did a quick review of your PR 8 hours after you said that it was ready.

Sure, I could have stopped working on my PR immediately when I saw that you opened yours, wait until you say that you are done, review your PR a few times until it is ready, merge it and then finish my own PR. I decided to finish my own work first and I don't think that it's fair to criticize me for doing that.

**Comment by AugierLe42e** [comment]
Ok, Sorry.

**Comment by cmrd-senya** [comment]
It's a nice thing to acknowledge other contributors that you're working
on some topic/issue/feature as soon as you have started it and decided
that you're going to make a pull request after a while. This way you can
arrange things before there is a conflict of yours change sets.

Also, makes it more comfortable to participate, when you see what other
people are working on. This helps to see the whole picture of what is
going on and to see your place in it. Helps to feel yourself more
included in the process.

**Comment by denschub** [comment]
Thank you for your kind words, @cmrd-senya. Seriously. I know it's not always easy, and there have been too many angry rants in the last time, so thank you very much.

It's true, Steffen could have interrupted Augier, or Augier could have interrupted Steffen. However, nobody did, so that happened. Who cares. @AugierLe42e, if you need help rebasing, I am sure Steffen might jump in. If not, I can do that as well. Let's not make another big story out of this, we can help each others out if a task gets too annoying (like rebasing), right?

**Pull request closed without merging**
